export let stateStationMap = {
    "ANDAMAN & NICOBAR": [
      { name: "CAMPBELL BAY", code: "CAMP" },
      { name: "CAR NICOBAR", code: "CARN" },
      { name: "CHIDIYA TAPU", code: "CHID" },
      { name: "DHARMAPUR", code: "DHPR" },
      { name: "HUTBAY", code: "HUTB" },
      { name: "KADAMTALA", code: "KADM" },
      { name: "KAMROTA", code: "KAMR" },
      { name: "KILSHORI NAGAR", code: "KILS" },
      { name: "LONG ISLAND", code: "LOIS" },
      { name: "MAYABUNDAR", code: "MAYA" },
      { name: "PHOENIXBAY", code: "PBAY" },
      { name: "SHAHEED DWEEP", code: "SHA1" },
      { name: "SHOALBAY", code: "SHOL" },
      { name: "SITANAGAR", code: "SITA" },
      { name: "SOUTH CREEK", code: "SEEK" },
      { name: "SWARAJDWEEP", code: "SEEP" },
    ],
    "ARUNACHAL PRADESH": [
      { name: "ARZOO", code: "ARZO" },
      { name: "BAANA", code: "BAAN" },
      { name: "BASAR", code: "BASA" },
      { name: "CHANGLANG", code: "CHGL" },
      { name: "DAPORIJO", code: "DAPO" },
      { name: "DIRANG", code: "DIRA" },
      { name: "HAWAI", code: "HAWA" },
      { name: "JANG", code: "JANG" },
      { name: "KAYING", code: "KAYI" },
      { name: "KHUPA", code: "KHUP" },
      { name: "KOLORIANG", code: "KOLO" },
      { name: "LIKABALI", code: "LIKA" },
      { name: "LONGDING", code: "LONG" },
      { name: "MANMAO", code: "MANM" },
      { name: "MARIYANG", code: "MARI" },
      { name: "MEBO", code: "MEBO" },
      { name: "MIAO", code: "MIAO" },
      { name: "MIGGING", code: "MIGG" },
      { name: "NAMSAI", code: "NAMS" },
      { name: "PALIN", code: "PALI" },
      { name: "PANGIN", code: "PANG" },
      { name: "ROING", code: "ROIN" },
      { name: "RUPA_AR", code: "RUP_" },
      { name: "SEIJOSA", code: "SEIJ" },
      { name: "SEPPA", code: "SEPA" },
      { name: "TEZU", code: "TEZU" },
      { name: "TUTING", code: "TUTI" },
      { name: "WALONG", code: "WALO" },
      { name: "YINGKIONG", code: "YING" },
      { name: "YUPIA", code: "YUPI" },
      { name: "ZIRO", code: "ZIRO" },
    ],
    ASSAM: [
      { name: "AMGURI", code: "AMGU" },
      { name: "AMTEKA", code: "AMTE" },
      { name: "BAKSA", code: "BAKS" },
      { name: "BARPETA", code: "BARP" },
      { name: "BIHUBOR", code: "BIHU" },
      { name: "BORLENGRI", code: "BORL" },
      { name: "CHAPAKHOWA", code: "CHPK" },
      { name: "CHAPAR", code: "CHPR" },
      { name: "CHARAIDEO", code: "CHRD" },
      { name: "DHAKUAKHANA", code: "DHAK" },
      { name: "DIBRUGARH", code: "DIBR" },
      { name: "DONKAMUKAM", code: "DONK" },
      { name: "FOTEHPUR", code: "FOTE" },
      { name: "GOGAMUKH", code: "GOGA" },
      { name: "GOLAGHAT", code: "GOLG" },
      { name: "GOLAKGANJ", code: "GOLA" },
      { name: "GUWAHATI", code: "GUW3" },
      { name: "HALOWANC", code: "HALO" },
      { name: "HELEM", code: "HELE" },
      { name: "JIRIGHAT", code: "JIRI" },
      { name: "JONAI", code: "JONA" },
      { name: "KACHUGAON", code: "KCHU" },
      { name: "KATIGORAH", code: "KTIG" },
      { name: "LUMDING", code: "LUMD" },
      { name: "MAIBANG", code: "MAIB" },
      { name: "MARGHERITA", code: "MARG" },
      { name: "MORIGAON", code: "MORG" },
      { name: "PHULONI", code: "PHLO" },
      { name: "RAJGHAT", code: "RAJG" },
      { name: "RAMKRISHNA", code: "RAMK" },
      { name: "SARUPATHAR", code: "SARU" },
      { name: "TEZPUR", code: "TEZP" },
      { name: "TINSUKIA", code: "TINS" },
      { name: "UDALGURI", code: "UDAL" },
      { name: "UMRONGSO", code: "UMRO" },
    ],
    BIHAR: [
      { name: "ARARIA", code: "ARAR" },
      { name: "BAGAHA", code: "BAGA" },
      { name: "BANKA", code: "BNKA" },
      { name: "BHABUA", code: "BHAB" },
      { name: "BIHARSHARIF", code: "BIHA" },
      { name: "BIRAUL", code: "BIRA" },
      { name: "BIRPUR", code: "BIRP" },
      { name: "BUXAR", code: "BUXA" },
      { name: "CHAKIA", code: "CHAK" },
      { name: "DAUDNAGAR", code: "DAUD" },
      { name: "DIGHALBANK", code: "DIGH" },
      { name: "DUMARIYA", code: "DUMA" },
      { name: "GAYA", code: "GAYA" },
      { name: "GOPALGANJ", code: "GOPA" },
      { name: "GWANAAHA", code: "GWAN" },
      { name: "JAGDISHPUR", code: "JAGD" },
      { name: "JAMUI", code: "JAMU" },
      { name: "JAYNAGAR", code: "JAYN" },
      { name: "KATIHAR", code: "KTHR" },
      { name: "KISHANGANJ", code: "KISH" },
      { name: "MADHEPURA", code: "MDHE" },
      { name: "MASHRAKH", code: "MASH" },
      { name: "MOKAMA", code: "MOKM" },
      { name: "MUNGER", code: "MNGE" },
      { name: "MUZAFFARPUR", code: "MUZA" },
      { name: "NAUGACHIA", code: "NUGH" },
      { name: "NAWADA", code: "NAWA" },
      { name: "PATNA", code: "PATN" },
      { name: "PHULPARAS", code: "PHUP" },
      { name: "PUPRI", code: "PUPR" },
      { name: "RATNIFARIDPUR", code: "RATN" },
      { name: "RAXAUL", code: "RAXA" },
      { name: "SAMASTIPUR", code: "SAMA" },
      { name: "SASARAM", code: "SASA" },
      { name: "THAKURGANJ", code: "THAK" },
    ],
    CHANDIGARH: [{ name: "CHANDIGARH", code: "CHDG" }],
    CHHATTISGARH: [
      { name: "BALOD", code: "BALO" },
      { name: "BASNA", code: "BASN" },
      { name: "BHATAPARA", code: "BHTP" },
      { name: "BIJAPUR", code: "BJPR" },
      { name: "BILASPURCG", code: "BLCG" },
      { name: "BODLA", code: "BODL" },
      { name: "CHIRMIRI", code: "CHRM" },
      { name: "GANDAI", code: "GDAI" },
      { name: "GEEDAM", code: "GEED" },
      { name: "JAGDALPUR", code: "JGDP" },
      { name: "JANAKPUR", code: "JNKP" },
      { name: "KANKER", code: "KNKR" },
      { name: "KARTALA", code: "KRTL" },
      { name: "KATGHORA", code: "KATG" },
      { name: "KONDAGAON", code: "KOND" },
      { name: "KUNKURI", code: "KUNK" },
      { name: "LAILUNGA", code: "LAIL" },
      { name: "LORMI", code: "LORM" },
      { name: "MAGARLOD", code: "MAGA" },
      { name: "MAHASAMUND", code: "MHND" },
      { name: "MAINPUR", code: "MAIN" },
      { name: "NARAYANPURCG", code: "NPCG" },
      { name: "PAKHANJUR", code: "PKHN" },
      { name: "PENDRAROAD", code: "PEND" },
      { name: "RAIGARH", code: "RAIG" },
      { name: "RAIPUR", code: "RAI3" },
      { name: "RAJNANDGAON", code: "RAJN" },
      { name: "SEORINARAYAN", code: "SERN" },
      { name: "SHANKARGARH", code: "SHAN" },
      { name: "SITAPUR", code: "STPR" },
      { name: "SURAJPUR", code: "SRJP" },
      { name: "WADRUPNAGAR", code: "WDRN" },
    ],
    DELHI: [{ name: "DELHIPALAM", code: "DELH" }],
    GOA: [
      { name: "CONCONA", code: "CONC" },
      { name: "DAYANADNAGAR", code: "DAAR" },
      { name: "TIVIM", code: "TIVI" },
    ],
    GUJARAT: [
      { name: "ADESAR", code: "ADER" },
      { name: "AHWA", code: "AHWA" },
      { name: "BAGASARA", code: "BAGR" },
      { name: "BALASAR", code: "BALA" },
      { name: "BACHAU", code: "BHAU" },
      { name: "BHAVNAGAR", code: "BHAV" },
      { name: "BHRINDIYARA", code: "BHRI" },
      { name: "BHUJ", code: "BHUJ" },
      { name: "BODELI", code: "BODE" },
      { name: "BOTAD", code: "BOTA" },
      { name: "BAYAD", code: "BYAD" },
      { name: "CHOTILA", code: "CHOL" },
      { name: "DAHOD", code: "DAHO" },
      { name: "DHARAMPUR", code: "DHAM" },
      { name: "DAHEJ", code: "DHEJ" },
      { name: "DHANDHUKA", code: "DHKA" },
      { name: "DHOLKA", code: "DHOL" },
      { name: "DAYAPAR", code: "DPAR" },
      { name: "GANDHINAGAR", code: "GAAR" },
      { name: "GONDAL", code: "GOAL" },
      { name: "GODHRA", code: "GODH" },
      { name: "HIMMATNAGAR", code: "HAGR" },
      { name: "ITI RAJKPT", code: "ITIR" },
      { name: "JAMNAGAR", code: "JAMN" },
      { name: "JAMBUSAR", code: "JSUR" },
      { name: "KABRADA", code: "KABR" },
      { name: "KALAWAD", code: "KAWD" },
      { name: "KHAMBHALIYA", code: "KHAB" },
      { name: "KOBG", code: "KOBG" },
      { name: "LALPUR", code: "LAL2" },
      { name: "LATHI", code: "LTHI" },
      { name: "MADHAVPUR", code: "MADV" },
      { name: "MAHUVA", code: "MAHU" },
      { name: "MANDAL", code: "MAN1" },
      { name: "MEHSANA", code: "MEHS" },
      { name: "MASKA", code: "MSKA" },
      { name: "NADIAD", code: "NADI" },
      { name: "NARALI", code: "NARL" },
      { name: "NALIYA", code: "NIYA" },
      { name: "NETRANG", code: "NTNG" },
      { name: "PALANPUR", code: "PALA" },
      { name: "PATAN", code: "PTAN" },
      { name: "SANTRAMPUR", code: "SANU" },
      { name: "SAVARKUNDLA", code: "SDLA" },
      { name: "SUIGAM", code: "SUIG" },
      { name: "SURAT", code: "SURA" },
      { name: "SURENDERNAGAR", code: "SURE" },
      { name: "TALALA", code: "TALA" },
      { name: "TANKARA", code: "TANK" },
      { name: "THARAD", code: "THAR" },
      { name: "UPLETA", code: "UPLE" },
      { name: "VADODARA", code: "VADO" },
      { name: "VARAHI", code: "VAHI" },
      { name: "VALSAD", code: "VALS" },
      { name: "VYARA", code: "VAR1" },
    ],
    HARYANA: [
      { name: "BHIWANI", code: "BHIW" },
      { name: "BHUNA", code: "BHUN" },
      { name: "GOHNA", code: "GOHN" },
      { name: "GORIWALA", code: "GORI" },
      { name: "GURGAON", code: "GURG" },
      { name: "HISAR", code: "HISA" },
      { name: "JHAJJAR", code: "JHAJ" },
      { name: "JIND", code: "JIND" },
      { name: "KAITHAL", code: "KAIT" },
      { name: "KARNAL", code: "KARN" },
      { name: "MAHENDRAGARH", code: "MAHE" },
      { name: "NARAYANGARH", code: "NARA" },
      { name: "NUH", code: "NUH_" },
      { name: "PALWAL", code: "PALW" },
      { name: "PANIPAT", code: "PANI" },
      { name: "REWARI", code: "REWA" },
      { name: "SHAHBAD", code: "SHAH" },
      { name: "SIRSA", code: "SIRS" },
      { name: "YAMUNANAGAR", code: "YAMU" },
    ],
    "HIMACHAL PRADESH": [
      { name: "AMBUNA", code: "AMBU" },
      { name: "CHAMBA", code: "CHAM" },
      { name: "CHAUPAL", code: "CHPL" },
      { name: "DHARMSHALA", code: "DHAR" },
      { name: "KULLU", code: "KULL" },
      { name: "NAHAN", code: "NAHA" },
      { name: "NURPUR", code: "NURP" },
      { name: "RAMPUR", code: "RMPR" },
      { name: "SHIMLA", code: "SHIM" },
      { name: "SUJANPUR", code: "SUJA" },
      { name: "SUNDERNAGAR", code: "SUND" },
    ],
    "JAMMU & KASHMIR": [
      { name: "BANDIPURA", code: "BAR1" },
      { name: "DODA", code: "DODA" },
      { name: "DOORU", code: "DORU" },
      { name: "JAMMU", code: "JMMU" },
      { name: "KATHUA", code: "KHUA" },
      { name: "KISHTWAR", code: "KIAR" },
      { name: "KUPWARA", code: "KURA" },
      { name: "MAHORE", code: "MARE" },
      { name: "SONMARG", code: "SARG" },
      { name: "SHOPIAN", code: "SOPN" },
      { name: "SRINAGAR", code: "SRIN" },
      { name: "SUNDERBANI", code: "SUNI" },
      { name: "SURANKOTE", code: "SUTE" },
      { name: "TANMARG", code: "TANG" },
      { name: "UDHAMPUR", code: "UDHM" },
    ],
    JHARKHAND: [
      { name: "BAGODHAR", code: "BAAR" },
      { name: "BARHAIT", code: "BARI" },
      { name: "BARWADIH", code: "BDIH" },
      { name: "BOKARO", code: "BORO" },
      { name: "BHAVANATHAPURI", code: "BPUR" },
      { name: "CHATRA", code: "CHAT" },
      { name: "CHITARPUR", code: "CHI1" },
      { name: "CHANDWA", code: "CHWA" },
      { name: "CHAKULIYA", code: "CHYA" },
      { name: "DHANBAD", code: "DBAD" },
      { name: "DEOGHAR", code: "DHA1" },
      { name: "DUMKA", code: "DMKA" },
      { name: "GIRDIH", code: "GDIH" },
      { name: "GUMLA", code: "GUMA" },
      { name: "HAZARIBAG", code: "HAAG" },
      { name: "HUSSAINABAD", code: "HUAD" },
      { name: "JAMSHEDPUR", code: "JAME" },
      { name: "JAMTARA", code: "JARA" },
      { name: "JAGANATHPUR", code: "JPUR" },
      { name: "JUMRI TALAIYA", code: "JUYA" },
      { name: "KHUNTPANI", code: "KANI" },
      { name: "MANOHARPUR SIG W", code: "MSIG" },
      { name: "PAKUR SADAR", code: "PAAR" },
      { name: "RANCHI", code: "RCHI" },
      { name: "SIMDEGA", code: "SEGA" },
      { name: "SUNDARPAHARI", code: "SUN1" },
      { name: "TAMAR", code: "TMAR" },
      { name: "TORPA", code: "TRPA" },
    ],
    KARNATAKA: [
      { name: "ALGUNDI", code: "AGNI" },
      { name: "ANKOLA", code: "ANKA" },
      { name: "ATHANI BELGAUM", code: "ATBM" },
      { name: "BANGALORE", code: "BANG" },
      { name: "BIDER", code: "BDER" },
      { name: "BANAVASI", code: "BNSI" },
      { name: "BANTWAL", code: "BNWl" },
      { name: "BASAVKLAYANA", code: "BSNA" },
      { name: "BHATKAL", code: "BTKL" },
      { name: "BHAGWATI", code: "BWTI" },
      { name: "CHANNAGIRI", code: "CNGR" },
      { name: "GUDIBANDE", code: "GBDE" },
      { name: "GULBARGA", code: "GBGA" },
      { name: "GOLGERI", code: "GGRI" },
      { name: "GOKAK", code: "GKAK" },
      { name: "GANDASI", code: "GNSI" },
      { name: "GURGUNTA", code: "GNTA" },
      { name: "HD KOTE", code: "HDTE" },
      { name: "HAGRIBOMANAHLLI", code: "HLLI" },
      { name: "HULIYAR", code: "HLYR" },
      { name: "HULIKUNTE", code: "HNTE" },
      { name: "JAGALURU", code: "JLRU" },
      { name: "KADUR", code: "KDUR" },
      { name: "KHANAPUR", code: "KHPR" },
      { name: "KOLAR", code: "KLAR" },
      { name: "KUNIGAL", code: "KNGL" },
      { name: "KANAKPUR", code: "KNRA" },
      { name: "KR PETE", code: "KPTE" },
      { name: "KUSTAGI", code: "KSGI" },
      { name: "LAXMESHWAR", code: "LXWR" },
      { name: "MUDDEBHIL", code: "MBIL" },
      { name: "MADHUGIRI", code: "MDGR" },
      { name: "MADDUR", code: "MDUR" },
      { name: "MUDIGERE", code: "MGRE" },
      { name: "PAVGADA", code: "PVDA" },
      { name: "RANEBENNUR", code: "RBUR" },
      { name: "RAICHURU", code: "RCRU" },
      { name: "RONA", code: "RONA" },
      { name: "SAUDATHI", code: "SDHI" },
      { name: "SEDAM", code: "SEDM" },
      { name: "SANDUR", code: "SNDR" },
      { name: "SINDANURU", code: "SNUR" },
      { name: "SOMWARPET", code: "SPET" },
      { name: "SHIKARPURA", code: "SPRA" },
      { name: "THIRITHAHALLI", code: "TLLI" },
      { name: "UDUPI", code: "UDPI" },
      { name: "VIJAYAPUR", code: "VJPR" },
      { name: "YADGIR", code: "YDGR" },
      { name: "YELANDUR", code: "YLDR" },
    ],
    KERALA: [
      { name: "ATHIRAPPILLY", code: "ALLY" },
      { name: "AZHOOR", code: "AOOR" },
      { name: "AMBLALAPUZHA", code: "AZHA" },
      { name: "BEKAL", code: "BKAL" },
      { name: "BEYPORE", code: "BORE" },
      { name: "CHUNDEL", code: "CDEL" },
      { name: "CHERPULASSERY", code: "CHE1" },
      { name: "CHITTUR", code: "CTUR" },
      { name: "EZHIMALA", code: "EALA" },
      { name: "KALLAYI", code: "KAY1" },
      { name: "KOZHANCHERRY", code: "KERY" },
      { name: "KELAKKAM", code: "KKAM" },
      { name: "KOLLAM", code: "KLAM" },
      { name: "KOCHI", code: "KOCH" },
      { name: "KUNJATTURU", code: "KUNJ" },
      { name: "KULATHUPZHA", code: "KZHA" },
      { name: "MANNAKUDDY", code: "MDDY" },
      { name: "MELUKAVUMATTA", code: "MTTA" },
      { name: "MUNNAR", code: "MUAR" },
      { name: "MUTHANGA", code: "MUGA" },
      { name: "NILAKKA", code: "NILA" },
      { name: "PONNANI", code: "PAN2" },
      { name: "PARAPPA", code: "PAPP" },
      { name: "PALLIPPURAM", code: "PLLI" },
      { name: "PUDDUR", code: "PUDD" },
      { name: "THIRUVANANTHAPUR", code: "TIR3" },
      { name: "THABORE", code: "TORE" },
      { name: "VAZHIKKADAVU", code: "VAVU" },
    ],
    LADAKH: [
      { name: "ABRAN", code: "ARAN" },
      { name: "BODHKHARBU", code: "BODH" },
      { name: "GYA", code: "GYAL" },
      { name: "HANUPATHA", code: "HNPA" },
      { name: "KARGIL", code: "KARG" },
      { name: "KIARI", code: "KIRI" },
      { name: "LEH", code: "LEH3" },
      { name: "PANG", code: "PAN1" },
      { name: "SANGRAH", code: "SAN1" },
      { name: "TANGTSE", code: "TANT" },
      { name: "Zangla", code: "ZANG" },
    ],
    LAKSHADWEEP: [
      { name: "AGATTI", code: "AGAT" },
      { name: "AMINI", code: "AMIN" },
      { name: "ANDROTH", code: "ANDR" },
      { name: "KAVARATTI", code: "KAVA" },
      { name: "MINICOY", code: "MINI" },
    ],
    "MADHYA PRADESH": [
      { name: "AJAYGARH", code: "AJAU" },
      { name: "ALIRAJPUR", code: "ALIR" },
      { name: "AMANGANI", code: "AMAN" },
      { name: "ANUPPUR", code: "ANPR" },
      { name: "ARON", code: "ARON" },
      { name: "ASHTA", code: "ASHT" },
      { name: "BABAI", code: "BABA" },
      { name: "BADAGAON", code: "BADA" },
      { name: "BADOD", code: "BADO" },
      { name: "BADUADA", code: "BADU" },
      { name: "BADWAHA", code: "BDWH" },
      { name: "BAIHAR", code: "BAIH" },
      { name: "BAJAG", code: "BAJA" },
      { name: "BAMORI", code: "BAMO" },
      { name: "BANDAMP", code: "BNMP" },
      { name: "BANKHEDI", code: "BANK" },
      { name: "BARHI", code: "BARH" },
      { name: "BEERPUR", code: "BEER" },
      { name: "BHAGWANPURA", code: "BHAG" },
      { name: "BHIMPUR", code: "BHIM" },
      { name: "BHINDNAGAR", code: "BHIN" },
      { name: "BICHUA", code: "BICH" },
      { name: "BIJAWAR", code: "BIJA" },
      { name: "BURHANPURNAGAR", code: "BURH" },
      { name: "CHANCHODA", code: "CHCH" },
      { name: "DALOD", code: "DALO" },
      { name: "DEORI", code: "DEOR" },
      { name: "DHAR", code: "DHHR" },
      { name: "DHEMARKEDA", code: "DHEM" },
      { name: "GAROTH", code: "GARO" },
      { name: "GHUGHRI", code: "GHUG" },
      { name: "GOTEGAON", code: "GOTE" },
      { name: "GULANA", code: "GULA" },
      { name: "GWALIOR", code: "GWAL" },
      { name: "HARRAI", code: "HARR" },
      { name: "HATPIPIYA", code: "HATP" },
      { name: "HUZURBHOPAL", code: "HUZU" },
      { name: "INDEGARH", code: "INDE" },
      { name: "INDORE", code: "INDO" },
      { name: "JABALPUR", code: "JABA" },
      { name: "JABERA", code: "JABE" },
      { name: "JAISINGHNAGAR", code: "JSNG" },
      { name: "JAMAIJUNARDEV", code: "JAMA" },
      { name: "JEERAPUR", code: "JEER" },
      { name: "JHABUA", code: "JHAB" },
      { name: "KAILARAS", code: "KAIL" },
      { name: "KARENA", code: "KARE" },
      { name: "KATANGI", code: "KATA" },
      { name: "KATINNAGAR", code: "KATI" },
      { name: "KHALWA", code: "KHAL" },
      { name: "KIRNAPUR", code: "KIRN" },
      { name: "KOTAR", code: "KOTA" },
      { name: "KUSMI", code: "KUSM" },
      { name: "LAKHADON", code: "LKDN" },
      { name: "MAHESHWAR", code: "MSWR" },
      { name: "MANASA", code: "MANA" },
      { name: "MANAWAR", code: "MNWR" },
      { name: "MOHANA", code: "MOHN" },
      { name: "MOHANGARH", code: "MHGR" },
      { name: "MUNGAOLI", code: "MUNG" },
      { name: "NAGDA", code: "NAGD" },
      { name: "NAINPUR", code: "NAIN" },
      { name: "NARSINGHGARH", code: "NARS" },
      { name: "NASRULLAGANJ", code: "NSRG" },
      { name: "NIWALI", code: "NIWA" },
      { name: "NIWAS", code: "NWAS" },
      { name: "NOWROZABAD", code: "NOWR" },
      { name: "PANDHANA", code: "PAND" },
      { name: "PATERA", code: "PATE" },
      { name: "POHARI", code: "POHA" },
      { name: "PORSA", code: "PORS" },
      { name: "PRABHATPATTAN", code: "PRAB" },
      { name: "RAHATGARH", code: "RAHA" },
      { name: "RAMPURNAIKAN", code: "RMNK" },
      { name: "RANNOD", code: "RANN" },
      { name: "RATLAM", code: "RATL" },
      { name: "SATWAS", code: "SAT3" },
      { name: "SEONINAGAR", code: "SEON" },
      { name: "SHAHPUR", code: "SHPR" },
      { name: "SIHAWAL", code: "SIHA" },
      { name: "SILWANI", code: "SILW" },
      { name: "SINGOLI", code: "SING" },
      { name: "SINGRAULINAGAR", code: "SRNG" },
      { name: "SIRALI", code: "SIRA" },
      { name: "SIRONJ", code: "SRNJ" },
      { name: "SULTANPURMP", code: "STMP" },
      { name: "TEOTHAR", code: "TEOT" },
      { name: "UJJAIN", code: "UJJA" },
      { name: "UNCHERA", code: "UNCH" },
      { name: "VIDISHA", code: "VIDI" },
    ],
    MAHARASHTRA: [
      { code: "AJRA", name: "AJARA" },
      { code: "AKLT", name: "AKALKOT" },
      { code: "AKOE", name: "AKOLE" },
      { code: "AKUA", name: "AKKALKUA" },
      { code: "ANER", name: "AMALNER" },
      { code: "APUR", name: "ACHALPUR" },
      { code: "ASTI", name: "ASHTI" },
      { code: "ATAL", name: "AKLUJ TAL" },
      { code: "BEED", name: "BEED" },
      { code: "BETL", name: "BEED TALUKA" },
      { code: "BHAN", name: "BHANDARA" },
      { code: "BHGN", name: "BHADGAON" },
      { code: "DAP1", name: "DAPOLI" },
      { code: "DAPR", name: "DAHANU PALGHAR" },
      { code: "DAU1", name: "DAUND" },
      { code: "DEND", name: "DEGLOOR NANDED" },
      { code: "DEOL", name: "DEOLI" },
      { code: "DGAB", name: "DEOGAON" },
      { code: "DHAN", name: "DHAN" },
      { code: "DHGN", name: "DHOLEGAON" },
      { code: "GDJM", name: "GODRI JAMNER" },
      { code: "GTNJ", name: "GHTANJI" },
      { code: "GWA1", name: "GHANSAWALI" },
      { code: "HKOL", name: "HATKANGALE KOLHA" },
      { code: "JALG", name: "JALGAON" },
      { code: "JINT", name: "JINTUR" },
      { code: "KAML", name: "KAMLESHWAR" },
      { code: "KCHI", name: "KORCHI" },
      { code: "KMGN", name: "KHAMGAON" },
      { code: "KNAG", name: "KESHAV NAGAR" },
      { code: "KNUR", name: "KALAMNURI" },
      { code: "KPUR", name: "KHANAPUR KARANJI" },
      { code: "KRSO", name: "KARAMALA SOLAPUR" },
      { code: "KSAT", name: "KARAD SATARA" },
      { code: "KVNI", name: "KANSHIVANI" },
      { code: "KWAN", name: "KALWAN" },
      { code: "LATU", name: "LATUR" },
      { code: "MAGN", name: "MAHAGAON" },
      { code: "MALE", name: "MALEGAON" },
      { code: "MAON", name: "MANGAON" },
      { code: "MEDH", name: "MEDHA" },
      { code: "MGAN", name: "MAHALGAON" },
      { code: "MLWN", name: "MALWAN" },
      { code: "MNRA", name: "MANORA" },
      { code: "MOHL", name: "MOHOL" },
      { code: "MULC", name: "MULC" },
      { code: "MULS", name: "MULS" },
      { code: "NANK", name: "NANDAGAON KHANDE" },
      { code: "NASK", name: "NASHIK" },
      { code: "NPGN", name: "NIPHAD DEOGAON" },
      { code: "NPUR", name: "NAVAPUR" },
      { code: "NTAL", name: "NANNDESWAR TAL" },
      { code: "PARL", name: "PARLI" },
      { code: "PLAM", name: "PALAM" },
      { code: "PTHN", name: "PAITHAN" },
      { code: "RAJU", name: "RAJURA" },
      { code: "RARI", name: "RAJAPUR RATNAGIR" },
      { code: "RHRI", name: "RAHURI AHMADNGR" },
      { code: "SAEN", name: "SADAK SHENDA" },
      { code: "SAHA", name: "SAHAPUR" },
      { code: "SAKR", name: "SAKRI" },
      { code: "SASW", name: "SASWAD" },
      { code: "SAWR", name: "SANGMESHWAR" },
      { code: "SHDA", name: "SHAHADA" },
      { code: "SHIR", name: "SHIRUR" },
      { code: "TELH", name: "TELHARA" },
      { code: "TGAN", name: "TALEGAON" },
      { code: "TUOD", name: "TUOD" },
      { code: "UDGR", name: "UDGIR" },
      { code: "UNAD", name: "UMARI NANDED" },
      { code: "UPVL", name: "UPVALE" },
      { code: "URAN", name: "URAN KARANJA" },
      { code: "VSAI", name: "VASAI" },
      { code: "WADG", name: "WADGAON" },
      { code: "WADS", name: "WADS" },
      { code: "WANI", name: "WANI" },
      { code: "YDSI", name: "YEDSHI" },
    ],
    MANIPUR: [
      { code: "CHKP", name: "CHAKPIKARONG" },
      { code: "CHNG", name: "CHINGAI" },
      { code: "IMPH", name: "IMPHAL" },
      { code: "KAMJ", name: "KAMJONG" },
      { code: "MCHI", name: "MACHI" },
      { code: "PHER", name: "PHERZAWL" },
      { code: "SENA", name: "SENAPATI" },
      { code: "SINT", name: "SINGHAT" },
      { code: "TAME", name: "TAMENGLONG" },
    ],
    MEGHALAYA: [
      { code: "AMPA", name: "AMPATI" },
      { code: "ARAD", name: "ARADONGA" },
      { code: "BAGH", name: "BAGHMARA" },
      { code: "CHER", name: "CHERRAPUNJI" },
      { code: "KHLI", name: "KHLIEHRIAT" },
      { code: "NAMD", name: "NAMDONG" },
      { code: "NONP", name: "NONGPOH" },
      { code: "NONG", name: "NONGSTOIN" },
      { code: "PHUB", name: "PHULBARI" },
      { code: "RANK", name: "RANIKOR" },
      { code: "RESU", name: "RESUBELPARA" },
      { code: "SHIL", name: "SHILLONG" },
      { code: "WILL", name: "WILLIAMNAGAR" },
    ],
    MIZORAM: [
      { code: "AIZA", name: "AIZAWL" },
      { code: "BILK", name: "BILKHAWTHLIR" },
      { code: "KAMA", name: "KAMALANAGAR" },
      { code: "KHAW", name: "KHAWZAWL" },
      { code: "LALL", name: "LALLEN" },
      { code: "NOGP", name: "NOGPA" },
      { code: "SANG", name: "SANGAU" },
      { code: "SERC", name: "SERCHHIP" },
      { code: "SOUB", name: "SOUTHBUNGTLANG" },
      { code: "SOUT", name: "SOUTHKHAWBUNG" },
      { code: "TUIP", name: "TUIPANG" },
      { code: "WEST", name: "WESTBUNGHMUM" },
    ],
    NAGALAND: [
      { code: "CHRE", name: "CHARE" },
      { code: "CHET", name: "CHETHEBA" },
      { code: "JALU", name: "JALUKIE" },
      { code: "MNKO", name: "MANGKOLEMBA" },
      { code: "MIMI", name: "MIMI" },
      { code: "NOKL", name: "NOKLAK" },
      { code: "PHOM", name: "PHOMCHING" },
      { code: "SANI", name: "SANIS" },
      { code: "TENI", name: "TENING" },
    ],
    ODISHA: [
      { code: "ASTA", name: "ASTARANGA" },
      { code: "BAA0", name: "BADAMPAHAR" },
      { code: "BAD1", name: "BARIPADA" },
      { code: "BADM", name: "BADMAL" },
      { code: "BAIR", name: "BALANGIR" },
      { code: "BAR2", name: "BARGARH" },
      { code: "BARK", name: "BARKOTE" },
      { code: "BGAR", name: "BHANJANAGAR" },
      { code: "BHAR", name: "BHADRAK" },
      { code: "BHOG", name: "BHOGRAI" },
      { code: "BHUW", name: "BHUBANESWAR" },
      { code: "BINI", name: "BINIKA" },
      { code: "BNDA", name: "BANGOMUNDA" },
      { code: "CPUR", name: "CHATRAPUR" },
      { code: "DARP", name: "DARPAN" },
      { code: "DAUR", name: "DASMANTHPUR" },
      { code: "DHAA", name: "DHAMARA" },
      { code: "DHAL", name: "DHENKANAL" },
      { code: "GAUD", name: "GAUDAGOTHA" },
      { code: "GIRI", name: "BRAHMAGIRI" },
      { code: "HARI", name: "HARICHANDANPUR" },
      { code: "JAM1", name: "JAMANKIRA" },
      { code: "KADA", name: "KADALIGARH" },
      { code: "KEON", name: "KEONJHAR" },
      { code: "KIRA", name: "KOIRA" },
      { code: "KUDA", name: "KURUDA" },
      { code: "KUNA", name: "KUNDURA" },
      { code: "KURH", name: "KUTRAGARH" },
      { code: "MAH1", name: "MAHAKALPADA" },
      { code: "MALK", name: "MALKANGIRI" },
      { code: "NABA", name: "NABARANGPUR" },
      { code: "NALA", name: "NARLA" },
      { code: "NAND", name: "NANDAPUR" },
      { code: "NAYA", name: "NAYAGARH" },
      { code: "NUAG", name: "NUAGAON" },
      { code: "NUAP", name: "NUAPADA" },
      { code: "PABR", name: "PABRITANAGAR" },
      { code: "PDMP", name: "PADAMPUR" },
      { code: "PHU1", name: "PHULBANI" },
      { code: "RAJ1", name: "RAJGANGPUR" },
      { code: "RARH", name: "RAYAGARH" },
      { code: "SARA", name: "SARAT" },
      { code: "TADA", name: "TANDABAI" },
      { code: "THUR", name: "THUAMUL RAMPUR" },
      { code: "TSRA", name: "TALSARA" },
      { code: "UDAY", name: "UDAYAGIRI" },
      { code: "UMAR", name: "UMARKOTE" },
      { code: "BOND", name: "BOINDA" },
    ],
    PUNJAB: [
      { code: "ABOH", name: "ABOHAR" },
      { code: "AMRI", name: "AMRITSAR" },
      { code: "ANAD", name: "ANADPURSAHIB" },
      { code: "BRLA", name: "BARNALA" },
      { code: "BHTD", name: "BHATINDA" },
      { code: "GURD", name: "GURDASPUR" },
      { code: "GURU", name: "GURUHARSAHAI" },
      { code: "JLND", name: "JALANDHAR" },
      { code: "LUDH", name: "LUDHIANA" },
      { code: "MANS", name: "MANSA" },
      { code: "MOGA", name: "MOGA" },
      { code: "NABH", name: "NABHA" },
      { code: "SUNA", name: "SUNAM" },
      { code: "TALW", name: "TALWARA" },
      { code: "TARN", name: "TARNTARAN" },
    ],
    RAJASTHAN: [
      { code: "AMAR", name: "AMARSAGAR" },
      { code: "AMET", name: "AMETH" },
      { code: "ARAI", name: "ARAIN" },
      { code: "BALE", name: "BALESAR" },
      { code: "BAMN", name: "BAMNOR" },
      { code: "BANS", name: "BANSWARA" },
      { code: "BHAK", name: "BHAKHASAR" },
      { code: "BKPR", name: "BIKAMPUR" },
      { code: "BIKA", name: "BIKANER" },
      { code: "BKRN", name: "BIKARNI" },
      { code: "BIKE", name: "BIKENDRI" },
      { code: "BUDS", name: "BUDSU" },
      { code: "CHDN", name: "CHANDAN" },
      { code: "CDWL", name: "CHANDAWAL" },
      { code: "CHAU", name: "CHAU" },
      { code: "CHIP", name: "CHIPPABAROD" },
      { code: "CHKR", name: "CHITTAKAPAR" },
      { code: "CHIT", name: "CHITTORGARH" },
      { code: "DANG", name: "DANGRI" },
      { code: "DAUS", name: "DAUSA" },
      { code: "DEGA", name: "DEGANAGAON" },
      { code: "DOBH", name: "DOBHI" },
      { code: "DOON", name: "DOONI" },
      { code: "DUDB", name: "DUDHABERI" },
      { code: "DHTL", name: "DUDHITALAI" },
      { code: "GANG", name: "GANGAPURCITY" },
      { code: "GHAR", name: "GHARSANA" },
      { code: "GOTA", name: "GOTAN" },
      { code: "GUDA", name: "GUDA" },
      { code: "HADD", name: "HADDA" },
      { code: "HANU", name: "HANUMANGARH" },
      { code: "JAIP", name: "JAIPUR" },
      { code: "JAIS", name: "JAISINDHAR" },
      { code: "JALO", name: "JALORE" },
      { code: "JASO", name: "JASORABAINA" },
      { code: "JHUN", name: "JHUNJHUNU" },
      { code: "JODH", name: "JODHPUR" },
      { code: "KARA", name: "KARANPURGANGAN" },
      { code: "KEKR", name: "KEKRI" },
      { code: "KHAJ", name: "KHAJUWALA" },
      { code: "KHAN", name: "KHANDELA" },
      { code: "KHIN", name: "KHINIYA" },
      { code: "LADN", name: "LADNU" },
      { code: "MAHW", name: "MAHWA" },
      { code: "MAND", name: "MANDAL" },
      { code: "MANG", name: "MANGLIVAWAS" },
      { code: "MOKA", name: "MOKALSAR" },
      { code: "MYAJ", name: "MYAJLAR" },
      { code: "NACH", name: "NACHNA" },
      { code: "NADO", name: "NADOL" },
      { code: "NRP3", name: "NARAYANPUR" },
      { code: "NAWG", name: "NAWGOAN" },
      { code: "NEEM", name: "NEEMKATHANA" },
      { code: "NIMA", name: "NIMA" },
      { code: "NWAI", name: "NIWAI" },
      { code: "OSIA", name: "OSIAN" },
      { code: "PCHL", name: "PACHALA" },
      { code: "PACH", name: "PACHPADRA" },
      { code: "PANC", name: "PANCHORI" },
      { code: "PHLD", name: "PHALODI" },
      { code: "PHAL", name: "PHALUSUND" },
      { code: "PHUL", name: "PHULERA" },
      { code: "POKH", name: "POKHRAN" },
      { code: "RJSR", name: "RAJASAR" },
      { code: "RAMG", name: "RAMGANIMANDI" },
      { code: "RANI", name: "RANIWAR" },
      { code: "RTNG", name: "RATANGARH" },
      { code: "RATA", name: "RATASAR" },
      { code: "RAWA", name: "RAWATSAR" },
      { code: "ROHA", name: "ROHAT" },
      { code: "RUPA", name: "RUPAHELIKALAN" },
      { code: "SADH", name: "SADHANA" },
      { code: "SADO", name: "SADOLAI" },
      { code: "SAGW", name: "SAGWARA" },
      { code: "SALU", name: "SALUMBER" },
      { code: "SANC", name: "SANCHORE" },
      { code: "SHRI", name: "SHRIVIJAYNAGAR" },
      { code: "SIKA", name: "SIKAR" },
      { code: "SIND", name: "SINDHARI" },
      { code: "SIRO", name: "SIROHI" },
      { code: "SRID", name: "SRIDUNGARGARH" },
      { code: "SPRJ", name: "SULTANPUTRJ" },
      { code: "TARA", name: "TARANAGAR" },
      { code: "VALL", name: "VALLABHNAGAR" },
      { code: "VISM", name: "VISMA" },
    ],
    SIKKIM: [
      { code: "GAN1", name: "GANGTOK" },
      { code: "LACH", name: "LACHUNG" },
      { code: "MAN2", name: "MANGAN" },
      { code: "YUKS", name: "YUKSOM" },
    ],
    "TAMIL NADU": [
      { code: "AGWM", name: "AGASTHASWEERAM" },
      { code: "ALAN", name: "ALANGUDI" },
      { code: "AMSM", name: "AMBASAMUTHRAM" },
      { code: "ANNU", name: "ANNUR" },
      { code: "ANTH", name: "ANTHIYUR" },
      { code: "ATUR", name: "ATHUR" },
      { code: "CHEY", name: "CHEYYUR" },
      { code: "CHN1", name: "CHENNAI" },
      { code: "CUDD", name: "CUDDALORE" },
      { code: "CYAR", name: "CHEYYAR" },
      { code: "GDLR", name: "GUDALUR" },
      { code: "GDYM", name: "GUDIYATHAM" },
      { code: "GNGI", name: "GINGEE" },
      { code: "GUMP", name: "GUMMIDIPOONDI" },
      { code: "HARU", name: "HARUR" },
      { code: "HSUR", name: "HOSUR" },
      { code: "KANC", name: "KANCHIPURAM" },
      { code: "KARU", name: "KARUR" },
      { code: "KDVR", name: "KADAVUR" },
      { code: "KGYM", name: "KANGEYAM" },
      { code: "KKDI", name: "KARAIKUDI" },
      { code: "KLKC", name: "KALLAKURICHI" },
      { code: "KLSP", name: "KALASAPAKKAM" },
      { code: "KMTH", name: "KAMUTHI" },
      { code: "KODA", name: "KODAIKANAL" },
      { code: "KOLI", name: "KOLLIHILLS" },
      { code: "KRIN", name: "KRISHNAGIRI" },
      { code: "KRYP", name: "KARIYAPATTI" },
      { code: "KTDU", name: "KINATHUKADAVU" },
      { code: "KTPD", name: "KATPADI" },
      { code: "KUDV", name: "KUDAVASAL" },
      { code: "KUND", name: "KUNDAH" },
      { code: "KVIL", name: "KOVILPATTI" },
      { code: "KZTH", name: "KUZITHURAI" },
      { code: "MDKL", name: "MADATHUKULAM" },
      { code: "MNME", name: "MAcodeLGUDI" },
      { code: "NAGA", name: "NAGAPATNAM" },
      { code: "NATR", name: "NILAKOTTAI" },
      { code: "NHAM", name: "NATHAM" },
      { code: "NLKT", name: "NATRAMPALLI" },
      { code: "ODDA", name: "ODDANCHATHRAM" },
      { code: "PBLU", name: "PERAMBALUR" },
      { code: "PLPT", name: "PALLIPATTU" },
      { code: "PNGM", name: "PENNAGARAM" },
      { code: "PRYU", name: "PERAIYUR" },
      { code: "PTTK", name: "PATTUKOTTAI" },
      { code: "PYKT", name: "PALAYAMKOTTAI" },
      { code: "RDHM", name: "RADHAPURAM" },
      { code: "RMND", name: "RAMANATHAPURAM" },
      { code: "SALM", name: "SALEM" },
      { code: "SGIR", name: "SIVAGIRI" },
      { code: "SIVA", name: "SIVAGANGAI" },
      { code: "SNTR", name: "SENTHURAI" },
      { code: "SRGM", name: "SRIRANGAM" },
      { code: "TALV", name: "TALAVADI" },
      { code: "TCGD", name: "THIRUCHENGODE" },
      { code: "TCND", name: "THIRUCHENDUR" },
      { code: "TDPT", name: "THANDRAMPATTU" },
      { code: "THIR", name: "THIRUPORUR" },
      { code: "TIRV", name: "THIRUVALLUR" },
      { code: "TNKS", name: "TENKASI" },
      { code: "TTKD", name: "THOOTHUKUDI" },
      { code: "TVYR", name: "THIRUVAIYARU" },
      { code: "ULUN", name: "ULUNDURPET" },
      { code: "UTPM", name: "UTHAMAPALAYAM" },
      { code: "VALP", name: "VALPARAI" },
      { code: "VEDA", name: "VEDHARANYAM" },
      { code: "VNUR", name: "VANUR" },
      { code: "KADI", name: "KADALADI" },
      { code: "KURI", name: "KURINJIPADI" },
      { code: "PNMY", name: "PONAMARAVATHY" },
      { code: "PUDU", name: "PUDUCHERRY" },
      { code: "RMWM", name: "RAMESHWARAM" },
      { code: "SKLI", name: "SIRKALI" },
      { code: "TVDI", name: "THIRUVADANAI" },
    ],
    TELANGANA: [
      { code: "ALLA", name: "ALLAPALLY" },
      { code: "AMRB", name: "AMRABAD" },
      { code: "ANDM", name: "ANDOLEMEDAK" },
      { code: "ANNA", name: "ANNAPUREDDYPALLY" },
      { code: "ASIF", name: "ASIFABAD" },
      { code: "BEJJ", name: "BEJJUR" },
      { code: "BELA", name: "BELA" },
      { code: "CHAR", name: "CHARLA" },
      { code: "CHNN", name: "CHINNACHINTAKUNTA" },
      { code: "CHIN", name: "CHINTHAPALLY" },
      { code: "ERGM", name: "ETURANAGARAM" },
      { code: "HYDE", name: "HYDERABAD" },
      { code: "KRMN", name: "KARIMNAGAR" },
      { code: "MACH", name: "MACHAREDDY" },
      { code: "MHPR", name: "MAHADEVPUR" },
      { code: "MNCH", name: "MANCHERIAL" },
      { code: "MEDI", name: "MEDIPALLI" },
      { code: "NGRK", name: "NAGARKURNOOL" },
      { code: "NRYP", name: "NARAYANPET" },
      { code: "NARK", name: "NARKETPALLY" },
      { code: "NEKK", name: "NEKKONDA" },
      { code: "NIDA", name: "NIDAMANOOR" },
      { code: "NIZM", name: "NIZAMABAD" },
      { code: "NIZA", name: "NIZAMSAGAR" },
      { code: "NOOT", name: "NOOTHANKAL" },
      { code: "PAMB", name: "PAMBI" },
      { code: "PNTV", name: "PENTAVELLY" },
      { code: "RGNP", name: "RAGHUNATHPALLY" },
      { code: "RJTG", name: "RAJAPURTG" },
      { code: "REGO", name: "REGONDA" },
      { code: "SARN", name: "SARANGPUR" },
      { code: "SHNT", name: "SHANTINAGAR" },
      { code: "TAMS", name: "TAMSI" },
      { code: "THOG", name: "THOGUTA" },
      { code: "VIKR", name: "VIKARABADH" },
    ],
    TRIPURA: [
      { code: "AGAR", name: "AGARTALA" },
      { code: "AMBA", name: "AMBASSA" },
      { code: "BANA", name: "BANABITI" },
      { code: "DASD", name: "DASDA" },
      { code: "DHRM", name: "DHARAMNAGAR" },
      { code: "GANC", name: "GANDACHERRA" },
      { code: "MANU", name: "MANUBAZAR" },
      { code: "MELA", name: "MELAGHAR" },
    ],
    "UTTAR PRADESH": [
      { code: "AKBA", name: "AKBARPUR" },
      { code: "ALIG", name: "ALIGANJ" },
      { code: "ALGR", name: "ALIGARH" },
      { code: "ANUP", name: "ANUPSHAHAR" },
      { code: "AURA", name: "AURAIYA" },
      { code: "BACH", name: "BACHHRAWAN" },
      { code: "BALR", name: "BALRAMPUR" },
      { code: "BAND", name: "BANDA" },
      { code: "BARA", name: "BARA" },
      { code: "BART", name: "BARAUT" },
      { code: "BILA", name: "BILASPUR" },
      { code: "BILG", name: "BILGRAM" },
      { code: "CHAN", name: "CHANDAUSI" },
      { code: "CHIB", name: "CHIBRAMAU" },
      { code: "DUDH", name: "DUDHI" },
      { code: "ETAW", name: "ETAWAH" },
      { code: "FARI", name: "FARIDPUR" },
      { code: "FATE", name: "FATEHPUR" },
      { code: "FIRO", name: "FIROZABAD" },
      { code: "GHAZ", name: "GHAZIPUR" },
      { code: "GORA", name: "GORAKHPUR" },
      { code: "HAMI", name: "HAMIRPUR" },
      { code: "HAPU", name: "HAPUR" },
      { code: "HARA", name: "HARAIYYA" },
      { code: "JALA", name: "JALALABAD" },
      { code: "JAUN", name: "JAUNPUR" },
      { code: "JHAN", name: "JHANSI" },
      { code: "KALP", name: "KALPI" },
      { code: "KANP", name: "KANPUR" },
      { code: "KAS3", name: "KASHGANJ" },
      { code: "KSRG", name: "KESHARGANJ" },
      { code: "KHAI", name: "KHAIRAGARH" },
      { code: "KHAR", name: "KHARIBAD" },
      { code: "KHTL", name: "KHATAULI" },
      { code: "KHUS", name: "KHUSHINAGAR" },
      { code: "KONC", name: "KONCH" },
      { code: "LAKH", name: "LAKHIMPUR" },
      { code: "LALG", name: "LALGANJ MIRZAPUR" },
      { code: "LALP", name: "LALGANJ PRATAPGARH" },
      { code: "LALI", name: "LALITPUR" },
      { code: "LUCK", name: "LUCKNOW" },
      { code: "MADH", name: "MADHUBANI" },
      { code: "MAHA", name: "MAHARAJGANJ" },
      { code: "MAHO", name: "MAHOBA" },
      { code: "MATH", name: "MATHURA" },
      { code: "MAUR", name: "MAURANIPUR" },
      { code: "MILK", name: "MILKIPUR" },
      { code: "MHMD", name: "MOHAMMADI" },
      { code: "NJBD", name: "NAJIBABAD" },
      { code: "NANP", name: "NANPARA" },
      { code: "NAUG", name: "NAUGARH" },
      { code: "NIGH", name: "NIGHASAN" },
      { code: "PARA", name: "PARASPUR" },
      { code: "PHNA", name: "PHEENA" },
      { code: "PHOO", name: "PHOOLPUR" },
      { code: "POOR", name: "POORANPUR" },
      { code: "RAJA", name: "RAJAPUR" },
      { code: "RAMP", name: "RAMPUR MANIHARAN" },
      { code: "RASR", name: "RASRA" },
      { code: "RATH", name: "RATH" },
      { code: "ROBT", name: "ROBERTSGANJ" },
      { code: "SAGR", name: "SAGRI" },
      { code: "SALE", name: "SALEMPUR" },
      { code: "SAND", name: "SANDILA" },
      { code: "SULT", name: "SULTANPUR" },
      { code: "VARA", name: "VARANASI" },
    ],
    UTTARAKHAND: [
      { code: "BAIJ", name: "BAIJNATH" },
      { code: "BHAT", name: "BHATWARI" },
      { code: "DEHD", name: "DEHRADUN" },
      { code: "HALD", name: "HALDWANI" },
      { code: "JOSH", name: "JOSHIMATH" },
      { code: "KHA3", name: "KHATIMA" },
      { code: "KULH", name: "KULHAL" },
      { code: "MORI", name: "MORI" },
      { code: "MUNS", name: "MUNSIYARI" },
      { code: "NTHR", name: "NEW TEHRI" },
      { code: "PITH", name: "PITHORAGARH" },
      { code: "RMNG", name: "RAM NAGAR" },
      { code: "ROO3", name: "ROORKEE" },
      { code: "RUDR", name: "RUDRA PRAYAG" },
      { code: "STPU", name: "SATPULI" },
    ],
    "WEST BENGAL": [
      { code: "ALIP", name: "ALIPURDUAR" },
      { code: "ARAM", name: "ARAMBAG" },
      { code: "ASAN", name: "ASANSOL" },
      { code: "BALU", name: "BALURGHAT" },
      { code: "BANO", name: "BANGAON" },
      { code: "BARD", name: "BARDHAMAN" },
      { code: "BASI", name: "BASIRHAT" },
      { code: "BEHA", name: "BEHARAMPUR" },
      { code: "BISH", name: "BISHNUPUR" },
      { code: "BOLP", name: "BOLPUR" },
      { code: "CANN", name: "CANNING" },
      { code: "CHHA", name: "CHHATNA" },
      { code: "CONT", name: "CONTIA" },
      { code: "DARJ", name: "DARJEELING" },
      { code: "DEBA", name: "DEBAGRAM" },
      { code: "DIAM", name: "DIAMONDH" },
      { code: "DINH", name: "DINHATA" },
      { code: "DURG", name: "DURGAPUR" },
      { code: "FALA", name: "FALAKATA" },
      { code: "JALP", name: "JALPAIGURI" },
      { code: "KARI", name: "KARIMPUR" },
      { code: "KAT1", name: "KATAMARI" },
      { code: "KHA1", name: "KHARAGPU" },
      { code: "KOLK", name: "KOLKATA" },
      { code: "KRIS", name: "KRISHNANAGAR" },
      { code: "KUMI", name: "KUMIRMARI" },
      { code: "LAL1", name: "LALGOLA" },
      { code: "MALB", name: "MALBAZAR" },
      { code: "MALD", name: "MALDA" },
      { code: "MANB", name: "MANBAZAR" },
      { code: "MOGR", name: "MOGRARA" },
      { code: "NAXA", name: "NAXALBARI" },
      { code: "PANS", name: "PANSKURA" },
      { code: "PURU", name: "PURULIYA" },
      { code: "RAI1", name: "RAIGANJ" },
      { code: "SAGA", name: "SAGARISL" },
      { code: "SAIN", name: "SAINTHIA" },
      { code: "SARE", name: "SARENGA" },
    ],
  };


export let stateStationMap1 = {
   UTTARAKHAND: [
    { code: "BAIJ", name: "BAIJNATH" },
    { code: "BHAT", name: "BHATWARI" },
    { code: "DEHD", name: "DEHRADUN" },
    { code: "HALD", name: "HALDWANI" },
    { code: "JOSH", name: "JOSHIMATH" },
    { code: "KHA3", name: "KHATIMA" },
    { code: "KULH", name: "KULHAL" },
    { code: "MORI", name: "MORI" },
    { code: "MUNS", name: "MUNSIYARI" },
    { code: "NTHR", name: "NEW TEHRI" },
    { code: "PITH", name: "PITHORAGARH" },
    { code: "RMNG", name: "RAM NAGAR" },
    { code: "ROO3", name: "ROORKEE" },
    { code: "RUDR", name: "RUDRA PRAYAG" },
    { code: "STPU", name: "SATPULI" },
  ],
   "UTTAR PRADESH": [
      { code: "AKBA", name: "AKBARPUR" },
      { code: "ALIG", name: "ALIGANJ" },
      { code: "ALGR", name: "ALIGARH" },
      { code: "ANUP", name: "ANUPSHAHAR" },
      { code: "AURA", name: "AURAIYA" },
      { code: "BACH", name: "BACHHRAWAN" },
      { code: "BALR", name: "BALRAMPUR" },
      { code: "BAND", name: "BANDA" },
      { code: "BARA", name: "BARA" },
      { code: "BART", name: "BARAUT" },
      { code: "BILA", name: "BILASPUR" },
      { code: "BILG", name: "BILGRAM" },
      { code: "CHAN", name: "CHANDAUSI" },
      { code: "CHIB", name: "CHIBRAMAU" },
      { code: "DUDH", name: "DUDHI" },
      { code: "ETAW", name: "ETAWAH" },
      { code: "FARI", name: "FARIDPUR" },
      { code: "FATE", name: "FATEHPUR" },
      { code: "FIRO", name: "FIROZABAD" },
      { code: "GHAZ", name: "GHAZIPUR" },
      { code: "GORA", name: "GORAKHPUR" },
      { code: "HAMI", name: "HAMIRPUR" },
      { code: "HAPU", name: "HAPUR" },
      { code: "HARA", name: "HARAIYYA" },
      { code: "JALA", name: "JALALABAD" },
      { code: "JAUN", name: "JAUNPUR" },
      { code: "JHAN", name: "JHANSI" },
      { code: "KALP", name: "KALPI" },
      { code: "KANP", name: "KANPUR" },
      { code: "KAS3", name: "KASHGANJ" },
      { code: "KSRG", name: "KESHARGANJ" },
      { code: "KHAI", name: "KHAIRAGARH" },
      { code: "KHAR", name: "KHARIBAD" },
      { code: "KHTL", name: "KHATAULI" },
      { code: "KHUS", name: "KHUSHINAGAR" },
      { code: "KONC", name: "KONCH" },
      { code: "LAKH", name: "LAKHIMPUR" },
      { code: "LALG", name: "LALGANJ MIRZAPUR" },
      { code: "LALP", name: "LALGANJ PRATAPGARH" },
      { code: "LALI", name: "LALITPUR" },
      { code: "LUCK", name: "LUCKNOW" },
      { code: "MADH", name: "MADHUBANI" },
      { code: "MAHA", name: "MAHARAJGANJ" },
      { code: "MAHO", name: "MAHOBA" },
      { code: "MATH", name: "MATHURA" },
      { code: "MAUR", name: "MAURANIPUR" },
      { code: "MILK", name: "MILKIPUR" },
      { code: "MHMD", name: "MOHAMMADI" },
      { code: "NJBD", name: "NAJIBABAD" },
      { code: "NANP", name: "NANPARA" },
      { code: "NAUG", name: "NAUGARH" },
      { code: "NIGH", name: "NIGHASAN" },
      { code: "PARA", name: "PARASPUR" },
      { code: "PHNA", name: "PHEENA" },
      { code: "PHOO", name: "PHOOLPUR" },
      { code: "POOR", name: "POORANPUR" },
      { code: "RAJA", name: "RAJAPUR" },
      { code: "RAMP", name: "RAMPUR MANIHARAN" },
      { code: "RASR", name: "RASRA" },
      { code: "RATH", name: "RATH" },
      { code: "ROBT", name: "ROBERTSGANJ" },
      { code: "SAGR", name: "SAGRI" },
      { code: "SALE", name: "SALEMPUR" },
      { code: "SAND", name: "SANDILA" },
      { code: "SULT", name: "SULTANPUR" },
      { code: "VARA", name: "VARANASI" },
    ],
     HARYANA: [
      { name: "BHIWANI", code: "BHIW" },
      { name: "BHUNA", code: "BHUN" },
      { name: "GOHNA", code: "GOHN" },
      { name: "GORIWALA", code: "GORI" },
      { name: "GURGAON", code: "GURG" },
      { name: "HISAR", code: "HISA" },
      { name: "JHAJJAR", code: "JHAJ" },
      { name: "JIND", code: "JIND" },
      { name: "KAITHAL", code: "KAIT" },
      { name: "KARNAL", code: "KARN" },
      { name: "MAHENDRAGARH", code: "MAHE" },
      { name: "NARAYANGARH", code: "NARA" },
      { name: "NUH", code: "NUH_" },
      { name: "PALWAL", code: "PALW" },
      { name: "PANIPAT", code: "PANI" },
      { name: "REWARI", code: "REWA" },
      { name: "SHAHBAD", code: "SHAH" },
      { name: "SIRSA", code: "SIRS" },
      { name: "YAMUNANAGAR", code: "YAMU" },
    ],
       PUNJAB: [
      { code: "ABOH", name: "ABOHAR" },
      { code: "AMRI", name: "AMRITSAR" },
      { code: "ANAD", name: "ANADPURSAHIB" },
      { code: "BRLA", name: "BARNALA" },
      { code: "BHTD", name: "BHATINDA" },
      { code: "GURD", name: "GURDASPUR" },
      { code: "GURU", name: "GURUHARSAHAI" },
      { code: "JLND", name: "JALANDHAR" },
      { code: "LUDH", name: "LUDHIANA" },
      { code: "MANS", name: "MANSA" },
      { code: "MOGA", name: "MOGA" },
      { code: "NABH", name: "NABHA" },
      { code: "SUNA", name: "SUNAM" },
      { code: "TALW", name: "TALWARA" },
      { code: "TARN", name: "TARNTARAN" },
    ],
    "HIMACHAL PRADESH": [
      { name: "AMBUNA", code: "AMBU" },
      { name: "CHAMBA", code: "CHAM" },
      { name: "CHAUPAL", code: "CHPL" },
      { name: "DHARMSHALA", code: "DHAR" },
      { name: "KULLU", code: "KULL" },
      { name: "NAHAN", code: "NAHA" },
      { name: "NURPUR", code: "NURP" },
      { name: "RAMPUR", code: "RMPR" },
      { name: "SHIMLA", code: "SHIM" },
      { name: "SUJANPUR", code: "SUJA" },
      { name: "SUNDERNAGAR", code: "SUND" },
    ],
    "MADHYA PRADESH": [
      { name: "AJAYGARH", code: "AJAU" },
      { name: "ALIRAJPUR", code: "ALIR" },
      { name: "AMANGANI", code: "AMAN" },
      { name: "ANUPPUR", code: "ANPR" },
      { name: "ARON", code: "ARON" },
      { name: "ASHTA", code: "ASHT" },
      { name: "BABAI", code: "BABA" },
      { name: "BADAGAON", code: "BADA" },
      { name: "BADOD", code: "BADO" },
      { name: "BADUADA", code: "BADU" },
      { name: "BADWAHA", code: "BDWH" },
      { name: "BAIHAR", code: "BAIH" },
      { name: "BAJAG", code: "BAJA" },
      { name: "BAMORI", code: "BAMO" },
      { name: "BANDAMP", code: "BNMP" },
      { name: "BANKHEDI", code: "BANK" },
      { name: "BARHI", code: "BARH" },
      { name: "BEERPUR", code: "BEER" },
      { name: "BHAGWANPURA", code: "BHAG" },
      { name: "BHIMPUR", code: "BHIM" },
      { name: "BHINDNAGAR", code: "BHIN" },
      { name: "BICHUA", code: "BICH" },
      { name: "BIJAWAR", code: "BIJA" },
      { name: "BURHANPURNAGAR", code: "BURH" },
      { name: "CHANCHODA", code: "CHCH" },
      { name: "DALOD", code: "DALO" },
      { name: "DEORI", code: "DEOR" },
      { name: "DHAR", code: "DHHR" },
      { name: "DHEMARKEDA", code: "DHEM" },
      { name: "GAROTH", code: "GARO" },
      { name: "GHUGHRI", code: "GHUG" },
      { name: "GOTEGAON", code: "GOTE" },
      { name: "GULANA", code: "GULA" },
      { name: "GWALIOR", code: "GWAL" },
      { name: "HARRAI", code: "HARR" },
      { name: "HATPIPIYA", code: "HATP" },
      { name: "HUZURBHOPAL", code: "HUZU" },
      { name: "INDEGARH", code: "INDE" },
      { name: "INDORE", code: "INDO" },
      { name: "JABALPUR", code: "JABA" },
      { name: "JABERA", code: "JABE" },
      { name: "JAISINGHNAGAR", code: "JSNG" },
      { name: "JAMAIJUNARDEV", code: "JAMA" },
      { name: "JEERAPUR", code: "JEER" },
      { name: "JHABUA", code: "JHAB" },
      { name: "KAILARAS", code: "KAIL" },
      { name: "KARENA", code: "KARE" },
      { name: "KATANGI", code: "KATA" },
      { name: "KATINNAGAR", code: "KATI" },
      { name: "KHALWA", code: "KHAL" },
      { name: "KIRNAPUR", code: "KIRN" },
      { name: "KOTAR", code: "KOTA" },
      { name: "KUSMI", code: "KUSM" },
      { name: "LAKHADON", code: "LKDN" },
      { name: "MAHESHWAR", code: "MSWR" },
      { name: "MANASA", code: "MANA" },
      { name: "MANAWAR", code: "MNWR" },
      { name: "MOHANA", code: "MOHN" },
      { name: "MOHANGARH", code: "MHGR" },
      { name: "MUNGAOLI", code: "MUNG" },
      { name: "NAGDA", code: "NAGD" },
      { name: "NAINPUR", code: "NAIN" },
      { name: "NARSINGHGARH", code: "NARS" },
      { name: "NASRULLAGANJ", code: "NSRG" },
      { name: "NIWALI", code: "NIWA" },
      { name: "NIWAS", code: "NWAS" },
      { name: "NOWROZABAD", code: "NOWR" },
      { name: "PANDHANA", code: "PAND" },
      { name: "PATERA", code: "PATE" },
      { name: "POHARI", code: "POHA" },
      { name: "PORSA", code: "PORS" },
      { name: "PRABHATPATTAN", code: "PRAB" },
      { name: "RAHATGARH", code: "RAHA" },
      { name: "RAMPURNAIKAN", code: "RMNK" },
      { name: "RANNOD", code: "RANN" },
      { name: "RATLAM", code: "RATL" },
      { name: "SATWAS", code: "SAT3" },
      { name: "SEONINAGAR", code: "SEON" },
      { name: "SHAHPUR", code: "SHPR" },
      { name: "SIHAWAL", code: "SIHA" },
      { name: "SILWANI", code: "SILW" },
      { name: "SINGOLI", code: "SING" },
      { name: "SINGRAULINAGAR", code: "SRNG" },
      { name: "SIRALI", code: "SIRA" },
      { name: "SIRONJ", code: "SRNJ" },
      { name: "SULTANPURMP", code: "STMP" },
      { name: "TEOTHAR", code: "TEOT" },
      { name: "UJJAIN", code: "UJJA" },
      { name: "UNCHERA", code: "UNCH" },
      { name: "VIDISHA", code: "VIDI" },
    ],
    TELANGANA: [
      {code: "ALLA", name: "ALLAPALLY" },
      {code: "AMRB", name: "AMRABAD" },
      {code: "ANDM", name: "ANDOLEMEDAK" },
      {code: "ANNA", name: "ANNAPUREDDYPALLY" },
      {code: "ASIF", name: "ASIFABAD" },
      {code: "BEJJ", name: "BEJJUR" },
      {code: "BELA", name: "BELA" },
      {code: "CHAR", name: "CHARLA" },
      {code: "CHNN", name: "CHINNACHINTAKUNTA" },
      {code: "CHIN", name: "CHINTHAPALLY" },
      {code: "ERGM", name: "ETURANAGARAM" },
      {code: "HYDE", name: "HYDERABAD" },
      {code: "KRMN", name: "KARIMNAGAR" },
      {code: "MACH", name: "MACHAREDDY" },
      {code: "MHPR", name: "MAHADEVPUR" },
      {code: "MNCH", name: "MANCHERIAL" },
      {code: "MEDI", name: "MEDIPALLI" },
      {code: "NGRK", name: "NAGARKURNOOL" },
      {code: "NRYP", name: "NARAYANPET" },
      {code: "NARK", name: "NARKETPALLY" },
      {code: "NEKK", name: "NEKKONDA" },
      {code: "NIDA", name: "NIDAMANOOR" },
      {code: "NIZM", name: "NIZAMABAD" },
      {code: "NIZA", name: "NIZAMSAGAR" },
      {code: "NOOT", name: "NOOTHANKAL" },
      {code: "PAMB", name: "PAMBI" },
      {code: "PNTV", name: "PENTAVELLY" },
      {code: "RGNP", name: "RAGHUNATHPALLY" },
      {code: "RJTG", name: "RAJAPURTG" },
      {code: "REGO", name: "REGONDA" },
      {code: "SARN", name: "SARANGPUR" },
      {code: "SHNT", name: "SHANTINAGAR" },
      {code: "TAMS", name: "TAMSI" },
      {code: "THOG", name: "THOGUTA" },
      {code: "VIKR", name: "VIKARABADH" },
    ],
      CHHATTISGARH: [
      { name: "BALOD", code: "BALO" },
      { name: "BASNA", code: "BASN" },
      { name: "BHATAPARA", code: "BHTP" },
      { name: "BIJAPUR", code: "BJPR" },
      { name: "BILASPURCG", code: "BLCG" },
      { name: "BODLA", code: "BODL" },
      { name: "CHIRMIRI", code: "CHRM" },
      { name: "GANDAI", code: "GDAI" },
      { name: "GEEDAM", code: "GEED" },
      { name: "JAGDALPUR", code: "JGDP" },
      { name: "JANAKPUR", code: "JNKP" },
      { name: "KANKER", code: "KNKR" },
      { name: "KARTALA", code: "KRTL" },
      { name: "KATGHORA", code: "KATG" },
      { name: "KONDAGAON", code: "KOND" },
      { name: "KUNKURI", code: "KUNK" },
      { name: "LAILUNGA", code: "LAIL" },
      { name: "LORMI", code: "LORM" },
      { name: "MAGARLOD", code: "MAGA" },
      { name: "MAHASAMUND", code: "MHND" },
      { name: "MAINPUR", code: "MAIN" },
      { name: "NARAYANPURCG", code: "NPCG" },
      { name: "PAKHANJUR", code: "PKHN" },
      { name: "PENDRAROAD", code: "PEND" },
      { name: "RAIGARH", code: "RAIG" },
      { name: "RAIPUR", code: "RAI3" },
      { name: "RAJNANDGAON", code: "RAJN" },
      { name: "SEORINARAYAN", code: "SERN" },
      { name: "SHANKARGARH", code: "SHAN" },
      { name: "SITAPUR", code: "STPR" },
      { name: "SURAJPUR", code: "SRJP" },
      { name: "WADRUPNAGAR", code: "WDRN" },
    ],
     BIHAR: [
      { name: "ARARIA", code: "ARAR" },
      { name: "BAGAHA", code: "BAGA" },
      { name: "BANKA", code: "BNKA" },
      { name: "BHABUA", code: "BHAB" },
      { name: "BIHARSHARIF", code: "BIHA" },
      { name: "BIRAUL", code: "BIRA" },
      { name: "BIRPUR", code: "BIRP" },
      { name: "BUXAR", code: "BUXA" },
      { name: "CHAKIA", code: "CHAK" },
      { name: "DAUDNAGAR", code: "DAUD" },
      { name: "DIGHALBANK", code: "DIGH" },
      { name: "DUMARIYA", code: "DUMA" },
      { name: "GAYA", code: "GAYA" },
      { name: "GOPALGANJ", code: "GOPA" },
      { name: "GWANAAHA", code: "GWAN" },
      { name: "JAGDISHPUR", code: "JAGD" },
      { name: "JAMUI", code: "JAMU" },
      { name: "JAYNAGAR", code: "JAYN" },
      { name: "KATIHAR", code: "KTHR" },
      { name: "KISHANGANJ", code: "KISH" },
      { name: "MADHEPURA", code: "MDHE" },
      { name: "MASHRAKH", code: "MASH" },
      { name: "MOKAMA", code: "MOKM" },
      { name: "MUNGER", code: "MNGE" },
      { name: "MUZAFFARPUR", code: "MUZA" },
      { name: "NAUGACHIA", code: "NUGH" },
      { name: "NAWADA", code: "NAWA" },
      { name: "PATNA", code: "PATN" },
      { name: "PHULPARAS", code: "PHUP" },
      { name: "PUPRI", code: "PUPR" },
      { name: "RATNIFARIDPUR", code: "RATN" },
      { name: "RAXAUL", code: "RAXA" },
      { name: "SAMASTIPUR", code: "SAMA" },
      { name: "SASARAM", code: "SASA" },
      { name: "THAKURGANJ", code: "THAK" },
    ],
    RAJASTHAN: [
       { code: "AMAR", name: "AMARSAGAR" },
       { code: "AMET", name: "AMETH" },
       { code: "ARAI", name: "ARAIN" },
       { code: "BALE", name: "BALESAR" },
       { code: "BAMN", name: "BAMNOR" },
       { code: "BANS", name: "BANSWARA" },
       { code: "BHAK", name: "BHAKHASAR" },
       { code: "BKPR", name: "BIKAMPUR" },
       { code: "BIKA", name: "BIKANER" },
       { code: "BKRN", name: "BIKARNI" },
       { code: "BIKE", name: "BIKENDRI" },
       { code: "BUDS", name: "BUDSU" },
       { code: "CHDN", name: "CHANDAN" },
       { code: "CDWL", name: "CHANDAWAL" },
       { code: "CHAU", name: "CHAU" },
       { code: "CHIP", name: "CHIPPABAROD" },
       { code: "CHKR", name: "CHITTAKAPAR" },
       { code: "CHIT", name: "CHITTORGARH" },
       { code: "DANG", name: "DANGRI" },
       { code: "DAUS", name: "DAUSA" },
       { code: "DEGA", name: "DEGANAGAON" },
       { code: "DOBH", name: "DOBHI" },
       { code: "DOON", name: "DOONI" },
       { code: "DUDB", name: "DUDHABERI" },
       { code: "DHTL", name: "DUDHITALAI" },
       { code: "GANG", name: "GANGAPURCITY" },
       { code: "GHAR", name: "GHARSANA" },
       { code: "GOTA", name: "GOTAN" },
       { code: "GUDA", name: "GUDA" },
       { code: "HADD", name: "HADDA" },
       { code: "HANU", name: "HANUMANGARH" },
       { code: "JAIP", name: "JAIPUR" },
       { code: "JAIS", name: "JAISINDHAR" },
       { code: "JALO", name: "JALORE" },
       { code: "JASO", name: "JASORABAINA" },
       { code: "JHUN", name: "JHUNJHUNU" },
       { code: "JODH", name: "JODHPUR" },
       { code: "KARA", name: "KARANPURGANGAN" },
       { code: "KEKR", name: "KEKRI" },
       { code: "KHAJ", name: "KHAJUWALA" },
       { code: "KHAN", name: "KHANDELA" },
       { code: "KHIN", name: "KHINIYA" },
       { code: "LADN", name: "LADNU" },
       { code: "MAHW", name: "MAHWA" },
       { code: "MAND", name: "MANDAL" },
       { code: "MANG", name: "MANGLIVAWAS" },
       { code: "MOKA", name: "MOKALSAR" },
       { code: "MYAJ", name: "MYAJLAR" },
       { code: "NACH", name: "NACHNA" },
       { code: "NADO", name: "NADOL" },
       { code: "NRP3", name: "NARAYANPUR" },
       { code: "NAWG", name: "NAWGOAN" },
       { code: "NEEM", name: "NEEMKATHANA" },
       { code: "NIMA", name: "NIMA" },
       { code: "NWAI", name: "NIWAI" },
       { code: "OSIA", name: "OSIAN" },
       { code: "PCHL", name: "PACHALA" },
       { code: "PACH", name: "PACHPADRA" },
       { code: "PANC", name: "PANCHORI" },
       { code: "PHLD", name: "PHALODI" },
       { code: "PHAL", name: "PHALUSUND" },
       { code: "PHUL", name: "PHULERA" },
       { code: "POKH", name: "POKHRAN" },
       { code: "RJSR", name: "RAJASAR" },
       { code: "RAMG", name: "RAMGANIMANDI" },
       { code: "RANI", name: "RANIWAR" },
       { code: "RTNG", name: "RATANGARH" },
       { code: "RATA", name: "RATASAR" },
       { code: "RAWA", name: "RAWATSAR" },
       { code: "ROHA", name: "ROHAT" },
       { code: "RUPA", name: "RUPAHELIKALAN" },
       { code: "SADH", name: "SADHANA" },
       { code: "SADO", name: "SADOLAI" },
       { code: "SAGW", name: "SAGWARA" },
       { code: "SALU", name: "SALUMBER" },
       { code: "SANC", name: "SANCHORE" },
       { code: "SHRI", name: "SHRIVIJAYNAGAR" },
       { code: "SIKA", name: "SIKAR" },
       { code: "SIND", name: "SINDHARI" },
       { code: "SIRO", name: "SIROHI" },
       { code: "SRID", name: "SRIDUNGARGARH" },
       { code: "SPRJ", name: "SULTANPUTRJ" },
       { code: "TARA", name: "TARANAGAR" },
       { code: "VALL", name: "VALLABHNAGAR" },
       { code: "VISM", name: "VISMA" },
     ],
      "ANDHRA PRADESH": [
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BETHAMCHARLA", code: "BRLA" },
      { name: "C.BELAGAL", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },
      { name: "BELUGUPPA", code: "BGPA" },


    ],
     ASSAM: [
      { name: "AMGURI", code: "AMGU" },
      { name: "AMTEKA", code: "AMTE" },
      { name: "BAKSA", code: "BAKS" },
      { name: "BARPETA", code: "BARP" },
      { name: "BIHUBOR", code: "BIHU" },
      { name: "BORLENGRI", code: "BORL" },
      { name: "CHAPAKHOWA", code: "CHPK" },
      { name: "CHAPAR", code: "CHPR" },
      { name: "CHARAIDEO", code: "CHRD" },
      { name: "DHAKUAKHANA", code: "DHAK" },
      { name: "DIBRUGARH", code: "DIBR" },
      { name: "DONKAMUKAM", code: "DONK" },
      { name: "FOTEHPUR", code: "FOTE" },
      { name: "GOGAMUKH", code: "GOGA" },
      { name: "GOLAGHAT", code: "GOLG" },
      { name: "GOLAKGANJ", code: "GOLA" },
      { name: "GUWAHATI", code: "GUW3" },
      { name: "HALOWANC", code: "HALO" },
      { name: "HELEM", code: "HELE" },
      { name: "JIRIGHAT", code: "JIRI" },
      { name: "JONAI", code: "JONA" },
      { name: "KACHUGAON", code: "KCHU" },
      { name: "KATIGORAH", code: "KTIG" },
      { name: "LUMDING", code: "LUMD" },
      { name: "MAIBANG", code: "MAIB" },
      { name: "MARGHERITA", code: "MARG" },
      { name: "MORIGAON", code: "MORG" },
      { name: "PHULONI", code: "PHLO" },
      { name: "RAJGHAT", code: "RAJG" },
      { name: "RAMKRISHNA", code: "RAMK" },
      { name: "SARUPATHAR", code: "SARU" },
      { name: "TEZPUR", code: "TEZP" },
      { name: "TINSUKIA", code: "TINS" },
      { name: "UDALGURI", code: "UDAL" },
      { name: "UMRONGSO", code: "UMRO" },
    ],
      MEGHALAYA: [
      { code: "AMPA", name: "AMPATI" },
      { code: "ARAD", name: "ARADONGA" },
      { code: "BAGH", name: "BAGHMARA" },
      { code: "CHER", name: "CHERRAPUNJI" },
      { code: "KHLI", name: "KHLIEHRIAT" },
      { code: "NAMD", name: "NAMDONG" },
      { code: "NONP", name: "NONGPOH" },
      { code: "NONG", name: "NONGSTOIN" },
      { code: "PHUB", name: "PHULBARI" },
      { code: "RANK", name: "RANIKOR" },
      { code: "RESU", name: "RESUBELPARA" },
      { code: "SHIL", name: "SHILLONG" },
      { code: "WILL", name: "WILLIAMNAGAR" },
    ],
      TRIPURA: [
      { code: "AGAR", name: "AGARTALA" },
      { code: "AMBA", name: "AMBASSA" },
      { code: "BANA", name: "BANABITI" },
      { code: "DASD", name: "DASDA" },
      { code: "DHRM", name: "DHARAMNAGAR" },
      { code: "GANC", name: "GANDACHERRA" },
      { code: "MANU", name: "MANUBAZAR" },
      { code: "MELA", name: "MELAGHAR" },
    ],
      MANIPUR: [
      { code: "CHKP", name: "CHAKPIKARONG" },
      { code: "CHNG", name: "CHINGAI" },
      { code: "IMPH", name: "IMPHAL" },
      { code: "KAMJ", name: "KAMJONG" },
      { code: "MCHI", name: "MACHI" },
      { code: "PHER", name: "PHERZAWL" },
      { code: "SENA", name: "SENAPATI" },
      { code: "SINT", name: "SINGHAT" },
      { code: "TAME", name: "TAMENGLONG" },
    ],
     NAGALAND: [
      { code: "CHRE", name: "CHARE" },
      { code: "CHET", name: "CHETHEBA" },
      { code: "JALU", name: "JALUKIE" },
      { code: "MNKO", name: "MANGKOLEMBA" },
      { code: "MIMI", name: "MIMI" },
      { code: "NOKL", name: "NOKLAK" },
      { code: "PHOM", name: "PHOMCHING" },
      { code: "SANI", name: "SANIS" },
      { code: "TENI", name: "TENING" },
    ],
   
    MIZORAM: [
      { code: "AIZA", name: "AIZAWL" },
      { code: "BILK", name: "BILKHAWTHLIR" },
      { code: "KAMA", name: "KAMALANAGAR" },
      { code: "KHAW", name: "KHAWZAWL" },
      { code: "LALL", name: "LALLEN" },
      { code: "NOGP", name: "NOGPA" },
      { code: "SANG", name: "SANGAU" },
      { code: "SERC", name: "SERCHHIP" },
      { code: "SOUB", name: "SOUTHBUNGTLANG" },
      { code: "SOUT", name: "SOUTHKHAWBUNG" },
      { code: "TUIP", name: "TUIPANG" },
      { code: "WEST", name: "WESTBUNGHMUM" },
    ],
  CHANDIGARH: [{ name: "CHANDIGARH", code: "CHDG" }],
 
  DELHI: [{ name: "DELHIPALAM", code: "DELH" }],
   "ARUNACHAL PRADESH": [
      { name: "ARZOO", code: "ARZO" },
      { name: "BAANA", code: "BAAN" },
      { name: "BASAR", code: "BASA" },
      { name: "CHANGLANG", code: "CHGL" },
      { name: "DAPORIJO", code: "DAPO" },
      { name: "DIRANG", code: "DIRA" },
      { name: "HAWAI", code: "HAWA" },
      { name: "JANG", code: "JANG" },
      { name: "KAYING", code: "KAYI" },
      { name: "KHUPA", code: "KHUP" },
      { name: "KOLORIANG", code: "KOLO" },
      { name: "LIKABALI", code: "LIKA" },
      { name: "LONGDING", code: "LONG" },
      { name: "MANMAO", code: "MANM" },
      { name: "MARIYANG", code: "MARI" },
      { name: "MEBO", code: "MEBO" },
      { name: "MIAO", code: "MIAO" },
      { name: "MIGGING", code: "MIGG" },
      { name: "NAMSAI", code: "NAMS" },
      { name: "PALIN", code: "PALI" },
      { name: "PANGIN", code: "PANG" },
      { name: "ROING", code: "ROIN" },
      { name: "RUPA_AR", code: "RUP_" },
      { name: "SEIJOSA", code: "SEIJ" },
      { name: "SEPPA", code: "SEPA" },
      { name: "TEZU", code: "TEZU" },
      { name: "TUTING", code: "TUTI" },
      { name: "WALONG", code: "WALO" },
      { name: "YINGKIONG", code: "YING" },
      { name: "YUPIA", code: "YUPI" },
      { name: "ZIRO", code: "ZIRO" },
    ],
  };
   
   
   
   

   
   
   

   
// /////////////////////////////////////////////
  export let stateStationMap2={
    "TAMIL NADU": [
      { code: "AGWM", name: "AGASTHASWEERAM" },
      { code: "ALAN", name: "ALANGUDI" },
      { code: "AMSM", name: "AMBASAMUTHRAM" },
      { code: "ANNU", name: "ANNUR" },
      { code: "ANTH", name: "ANTHIYUR" },
      { code: "ATUR", name: "ATHUR" },
      { code: "CHEY", name: "CHEYYUR" },
      { code: "CHN1", name: "CHENNAI" },
      { code: "CUDD", name: "CUDDALORE" },
      { code: "CYAR", name: "CHEYYAR" },
      { code: "GDLR", name: "GUDALUR" },
      { code: "GDYM", name: "GUDIYATHAM" },
      { code: "GNGI", name: "GINGEE" },
      { code: "GUMP", name: "GUMMIDIPOONDI" },
      { code: "HARU", name: "HARUR" },
      { code: "HSUR", name: "HOSUR" },
      { code: "KANC", name: "KANCHIPURAM" },
      { code: "KARU", name: "KARUR" },
      { code: "KDVR", name: "KADAVUR" },
      { code: "KGYM", name: "KANGEYAM" },
      { code: "KKDI", name: "KARAIKUDI" },
      { code: "KLKC", name: "KALLAKURICHI" },
      { code: "KLSP", name: "KALASAPAKKAM" },
      { code: "KMTH", name: "KAMUTHI" },
      { code: "KODA", name: "KODAIKANAL" },
      { code: "KOLI", name: "KOLLIHILLS" },
      { code: "KRIN", name: "KRISHNAGIRI" },
      { code: "KRYP", name: "KARIYAPATTI" },
      { code: "KTDU", name: "KINATHUKADAVU" },
      { code: "KTPD", name: "KATPADI" },
      { code: "KUDV", name: "KUDAVASAL" },
      { code: "KUND", name: "KUNDAH" },
      { code: "KVIL", name: "KOVILPATTI" },
      { code: "KZTH", name: "KUZITHURAI" },
      { code: "MDKL", name: "MADATHUKULAM" },
      { code: "MNME", name: "MAcodeLGUDI" },
      { code: "NAGA", name: "NAGAPATNAM" },
      { code: "NATR", name: "NILAKOTTAI" },
      { code: "NHAM", name: "NATHAM" },
      { code: "NLKT", name: "NATRAMPALLI" },
      { code: "ODDA", name: "ODDANCHATHRAM" },
      { code: "PBLU", name: "PERAMBALUR" },
      { code: "PLPT", name: "PALLIPATTU" },
      { code: "PNGM", name: "PENNAGARAM" },
      { code: "PRYU", name: "PERAIYUR" },
      { code: "PTTK", name: "PATTUKOTTAI" },
      { code: "PYKT", name: "PALAYAMKOTTAI" },
      { code: "RDHM", name: "RADHAPURAM" },
      { code: "RMND", name: "RAMANATHAPURAM" },
      { code: "SALM", name: "SALEM" },
      { code: "SGIR", name: "SIVAGIRI" },
      { code: "SIVA", name: "SIVAGANGAI" },
      { code: "SNTR", name: "SENTHURAI" },
      { code: "SRGM", name: "SRIRANGAM" },
      { code: "TALV", name: "TALAVADI" },
      { code: "TCGD", name: "THIRUCHENGODE" },
      { code: "TCND", name: "THIRUCHENDUR" },
      { code: "TDPT", name: "THANDRAMPATTU" },
      { code: "THIR", name: "THIRUPORUR" },
      { code: "TIRV", name: "THIRUVALLUR" },
      { code: "TNKS", name: "TENKASI" },
      { code: "TTKD", name: "THOOTHUKUDI" },
      { code: "TVYR", name: "THIRUVAIYARU" },
      { code: "ULUN", name: "ULUNDURPET" },
      { code: "UTPM", name: "UTHAMAPALAYAM" },
      { code: "VALP", name: "VALPARAI" },
      { code: "VEDA", name: "VEDHARANYAM" },
      { code: "VNUR", name: "VANUR" },
      { code: "KADI", name: "KADALADI" },
      { code: "KURI", name: "KURINJIPADI" },
      { code: "PNMY", name: "PONAMARAVATHY" },
      { code: "PUDU", name: "PUDUCHERRY" },
      { code: "RMWM", name: "RAMESHWARAM" },
      { code: "SKLI", name: "SIRKALI" },
      { code: "TVDI", name: "THIRUVADANAI" },
    ],
     MAHARASHTRA: [
      { code: "AJRA", name: "AJARA" },
      { code: "AKLT", name: "AKALKOT" },
      { code: "AKOE", name: "AKOLE" },
      { code: "AKUA", name: "AKKALKUA" },
      { code: "ANER", name: "AMALNER" },
      { code: "APUR", name: "ACHALPUR" },
      { code: "ASTI", name: "ASHTI" },
      { code: "ATAL", name: "AKLUJ TAL" },
      { code: "BEED", name: "BEED" },
      { code: "BETL", name: "BEED TALUKA" },
      { code: "BHAN", name: "BHANDARA" },
      { code: "BHGN", name: "BHADGAON" },
      { code: "DAP1", name: "DAPOLI" },
      { code: "DAPR", name: "DAHANU PALGHAR" },
      { code: "DAU1", name: "DAUND" },
      { code: "DEND", name: "DEGLOOR NANDED" },
      { code: "DEOL", name: "DEOLI" },
      { code: "DGAB", name: "DEOGAON" },
      { code: "DHAN", name: "DHAN" },
      { code: "DHGN", name: "DHOLEGAON" },
      { code: "GDJM", name: "GODRI JAMNER" },
      { code: "GTNJ", name: "GHTANJI" },
      { code: "GWA1", name: "GHANSAWALI" },
      { code: "HKOL", name: "HATKANGALE KOLHA" },
      { code: "JALG", name: "JALGAON" },
      { code: "JINT", name: "JINTUR" },
      { code: "KAML", name: "KAMLESHWAR" },
      { code: "KCHI", name: "KORCHI" },
      { code: "KMGN", name: "KHAMGAON" },
      { code: "KNAG", name: "KESHAV NAGAR" },
      { code: "KNUR", name: "KALAMNURI" },
      { code: "KPUR", name: "KHANAPUR KARANJI" },
      { code: "KRSO", name: "KARAMALA SOLAPUR" },
      { code: "KSAT", name: "KARAD SATARA" },
      { code: "KVNI", name: "KANSHIVANI" },
      { code: "KWAN", name: "KALWAN" },
      { code: "LATU", name: "LATUR" },
      { code: "MAGN", name: "MAHAGAON" },
      { code: "MALE", name: "MALEGAON" },
      { code: "MAON", name: "MANGAON" },
      { code: "MEDH", name: "MEDHA" },
      { code: "MGAN", name: "MAHALGAON" },
      { code: "MLWN", name: "MALWAN" },
      { code: "MNRA", name: "MANORA" },
      { code: "MOHL", name: "MOHOL" },
      { code: "MULC", name: "MULC" },
      { code: "MULS", name: "MULS" },
      { code: "NANK", name: "NANDAGAON KHANDE" },
      { code: "NASK", name: "NASHIK" },
      { code: "NPGN", name: "NIPHAD DEOGAON" },
      { code: "NPUR", name: "NAVAPUR" },
      { code: "NTAL", name: "NANNDESWAR TAL" },
      { code: "PARL", name: "PARLI" },
      { code: "PLAM", name: "PALAM" },
      { code: "PTHN", name: "PAITHAN" },
      { code: "RAJU", name: "RAJURA" },
      { code: "RARI", name: "RAJAPUR RATNAGIR" },
      { code: "RHRI", name: "RAHURI AHMADNGR" },
      { code: "SAEN", name: "SADAK SHENDA" },
      { code: "SAHA", name: "SAHAPUR" },
      { code: "SAKR", name: "SAKRI" },
      { code: "SASW", name: "SASWAD" },
      { code: "SAWR", name: "SANGMESHWAR" },
      { code: "SHDA", name: "SHAHADA" },
      { code: "SHIR", name: "SHIRUR" },
      { code: "TELH", name: "TELHARA" },
      { code: "TGAN", name: "TALEGAON" },
      { code: "TUOD", name: "TUOD" },
      { code: "UDGR", name: "UDGIR" },
      { code: "UNAD", name: "UMARI NANDED" },
      { code: "UPVL", name: "UPVALE" },
      { code: "URAN", name: "URAN KARANJA" },
      { code: "VSAI", name: "VASAI" },
      { code: "WADG", name: "WADGAON" },
      { code: "WADS", name: "WADS" },
      { code: "WANI", name: "WANI" },
      { code: "YDSI", name: "YEDSHI" },
    ],
     GOA: [
      { name: "CONCONA", code: "CONC" },
      { name: "DAYANADNAGAR", code: "DAAR" },
      { name: "TIVIM", code: "TIVI" },
    ],
     KARNATAKA: [
      { name: "ALGUNDI", code: "AGNI" },
      { name: "ANKOLA", code: "ANKA" },
      { name: "ATHANI BELGAUM", code: "ATBM" },
      { name: "BANGALORE", code: "BANG" },
      { name: "BIDER", code: "BDER" },
      { name: "BANAVASI", code: "BNSI" },
      { name: "BANTWAL", code: "BNWl" },
      { name: "BASAVKLAYANA", code: "BSNA" },
      { name: "BHATKAL", code: "BTKL" },
      { name: "BHAGWATI", code: "BWTI" },
      { name: "CHANNAGIRI", code: "CNGR" },
      { name: "GUDIBANDE", code: "GBDE" },
      { name: "GULBARGA", code: "GBGA" },
      { name: "GOLGERI", code: "GGRI" },
      { name: "GOKAK", code: "GKAK" },
      { name: "GANDASI", code: "GNSI" },
      { name: "GURGUNTA", code: "GNTA" },
      { name: "HD KOTE", code: "HDTE" },
      { name: "HAGRIBOMANAHLLI", code: "HLLI" },
      { name: "HULIYAR", code: "HLYR" },
      { name: "HULIKUNTE", code: "HNTE" },
      { name: "JAGALURU", code: "JLRU" },
      { name: "KADUR", code: "KDUR" },
      { name: "KHANAPUR", code: "KHPR" },
      { name: "KOLAR", code: "KLAR" },
      { name: "KUNIGAL", code: "KNGL" },
      { name: "KANAKPUR", code: "KNRA" },
      { name: "KR PETE", code: "KPTE" },
      { name: "KUSTAGI", code: "KSGI" },
      { name: "LAXMESHWAR", code: "LXWR" },
      { name: "MUDDEBHIL", code: "MBIL" },
      { name: "MADHUGIRI", code: "MDGR" },
      { name: "MADDUR", code: "MDUR" },
      { name: "MUDIGERE", code: "MGRE" },
      { name: "PAVGADA", code: "PVDA" },
      { name: "RANEBENNUR", code: "RBUR" },
      { name: "RAICHURU", code: "RCRU" },
      { name: "RONA", code: "RONA" },
      { name: "SAUDATHI", code: "SDHI" },
      { name: "SEDAM", code: "SEDM" },
      { name: "SANDUR", code: "SNDR" },
      { name: "SINDANURU", code: "SNUR" },
      { name: "SOMWARPET", code: "SPET" },
      { name: "SHIKARPURA", code: "SPRA" },
      { name: "THIRITHAHALLI", code: "TLLI" },
      { name: "UDUPI", code: "UDPI" },
      { name: "VIJAYAPUR", code: "VJPR" },
      { name: "YADGIR", code: "YDGR" },
      { name: "YELANDUR", code: "YLDR" },
    ],
    KERALA: [
      { name: "ATHIRAPPILLY", code: "ALLY" },
      { name: "AZHOOR", code: "AOOR" },
      { name: "AMBLALAPUZHA", code: "AZHA" },
      { name: "BEKAL", code: "BKAL" },
      { name: "BEYPORE", code: "BORE" },
      { name: "CHUNDEL", code: "CDEL" },
      { name: "CHERPULASSERY", code: "CHE1" },
      { name: "CHITTUR", code: "CTUR" },
      { name: "EZHIMALA", code: "EALA" },
      { name: "KALLAYI", code: "KAY1" },
      { name: "KOZHANCHERRY", code: "KERY" },
      { name: "KELAKKAM", code: "KKAM" },
      { name: "KOLLAM", code: "KLAM" },
      { name: "KOCHI", code: "KOCH" },
      { name: "KUNJATTURU", code: "KUNJ" },
      { name: "KULATHUPZHA", code: "KZHA" },
      { name: "MANNAKUDDY", code: "MDDY" },
      { name: "MELUKAVUMATTA", code: "MTTA" },
      { name: "MUNNAR", code: "MUAR" },
      { name: "MUTHANGA", code: "MUGA" },
      { name: "NILAKKA", code: "NILA" },
      { name: "PONNANI", code: "PAN2" },
      { name: "PARAPPA", code: "PAPP" },
      { name: "PALLIPPURAM", code: "PLLI" },
      { name: "PUDDUR", code: "PUDD" },
      { name: "THIRUVANANTHAPUR", code: "TIR3" },
      { name: "THABORE", code: "TORE" },
      { name: "VAZHIKKADAVU", code: "VAVU" },
    ],
     GUJARAT: [
      { name: "ADESAR", code: "ADER" },
      { name: "AHWA", code: "AHWA" },
      { name: "BAGASARA", code: "BAGR" },
      { name: "BALASAR", code: "BALA" },
      { name: "BACHAU", code: "BHAU" },
      { name: "BHAVNAGAR", code: "BHAV" },
      { name: "BHRINDIYARA", code: "BHRI" },
      { name: "BHUJ", code: "BHUJ" },
      { name: "BODELI", code: "BODE" },
      { name: "BOTAD", code: "BOTA" },
      { name: "BAYAD", code: "BYAD" },
      { name: "CHOTILA", code: "CHOL" },
      { name: "DAHOD", code: "DAHO" },
      { name: "DHARAMPUR", code: "DHAM" },
      { name: "DAHEJ", code: "DHEJ" },
      { name: "DHANDHUKA", code: "DHKA" },
      { name: "DHOLKA", code: "DHOL" },
      { name: "DAYAPAR", code: "DPAR" },
      { name: "GANDHINAGAR", code: "GAAR" },
      { name: "GONDAL", code: "GOAL" },
      { name: "GODHRA", code: "GODH" },
      { name: "HIMMATNAGAR", code: "HAGR" },
      { name: "ITI RAJKPT", code: "ITIR" },
      { name: "JAMNAGAR", code: "JAMN" },
      { name: "JAMBUSAR", code: "JSUR" },
      { name: "KABRADA", code: "KABR" },
      { name: "KALAWAD", code: "KAWD" },
      { name: "KHAMBHALIYA", code: "KHAB" },
      { name: "KOBG", code: "KOBG" },
      { name: "LALPUR", code: "LAL2" },
      { name: "LATHI", code: "LTHI" },
      { name: "MADHAVPUR", code: "MADV" },
      { name: "MAHUVA", code: "MAHU" },
      { name: "MANDAL", code: "MAN1" },
      { name: "MEHSANA", code: "MEHS" },
      { name: "MASKA", code: "MSKA" },
      { name: "NADIAD", code: "NADI" },
      { name: "NARALI", code: "NARL" },
      { name: "NALIYA", code: "NIYA" },
      { name: "NETRANG", code: "NTNG" },
      { name: "PALANPUR", code: "PALA" },
      { name: "PATAN", code: "PTAN" },
      { name: "SANTRAMPUR", code: "SANU" },
      { name: "SAVARKUNDLA", code: "SDLA" },
      { name: "SUIGAM", code: "SUIG" },
      { name: "SURAT", code: "SURA" },
      { name: "SURENDERNAGAR", code: "SURE" },
      { name: "TALALA", code: "TALA" },
      { name: "TANKARA", code: "TANK" },
      { name: "THARAD", code: "THAR" },
      { name: "UPLETA", code: "UPLE" },
      { name: "VADODARA", code: "VADO" },
      { name: "VARAHI", code: "VAHI" },
      { name: "VALSAD", code: "VALS" },
      { name: "VYARA", code: "VAR1" },
    ],
     ODISHA: [
      { code: "ASTA", name: "ASTARANGA" },
      { code: "BAA0", name: "BADAMPAHAR" },
      { code: "BAD1", name: "BARIPADA" },
      { code: "BADM", name: "BADMAL" },
      { code: "BAIR", name: "BALANGIR" },
      { code: "BAR2", name: "BARGARH" },
      { code: "BARK", name: "BARKOTE" },
      { code: "BGAR", name: "BHANJANAGAR" },
      { code: "BHAR", name: "BHADRAK" },
      { code: "BHOG", name: "BHOGRAI" },
      { code: "BHUW", name: "BHUBANESWAR" },
      { code: "BINI", name: "BINIKA" },
      { code: "BNDA", name: "BANGOMUNDA" },
      { code: "CPUR", name: "CHATRAPUR" },
      { code: "DARP", name: "DARPAN" },
      { code: "DAUR", name: "DASMANTHPUR" },
      { code: "DHAA", name: "DHAMARA" },
      { code: "DHAL", name: "DHENKANAL" },
      { code: "GAUD", name: "GAUDAGOTHA" },
      { code: "GIRI", name: "BRAHMAGIRI" },
      { code: "HARI", name: "HARICHANDANPUR" },
      { code: "JAM1", name: "JAMANKIRA" },
      { code: "KADA", name: "KADALIGARH" },
      { code: "KEON", name: "KEONJHAR" },
      { code: "KIRA", name: "KOIRA" },
      { code: "KUDA", name: "KURUDA" },
      { code: "KUNA", name: "KUNDURA" },
      { code: "KURH", name: "KUTRAGARH" },
      { code: "MAH1", name: "MAHAKALPADA" },
      { code: "MALK", name: "MALKANGIRI" },
      { code: "NABA", name: "NABARANGPUR" },
      { code: "NALA", name: "NARLA" },
      { code: "NAND", name: "NANDAPUR" },
      { code: "NAYA", name: "NAYAGARH" },
      { code: "NUAG", name: "NUAGAON" },
      { code: "NUAP", name: "NUAPADA" },
      { code: "PABR", name: "PABRITANAGAR" },
      { code: "PDMP", name: "PADAMPUR" },
      { code: "PHU1", name: "PHULBANI" },
      { code: "RAJ1", name: "RAJGANGPUR" },
      { code: "RARH", name: "RAYAGARH" },
      { code: "SARA", name: "SARAT" },
      { code: "TADA", name: "TANDABAI" },
      { code: "THUR", name: "THUAMUL RAMPUR" },
      { code: "TSRA", name: "TALSARA" },
      { code: "UDAY", name: "UDAYAGIRI" },
      { code: "UMAR", name: "UMARKOTE" },
      { code: "BOND", name: "BOINDA" },
    ],
     SIKKIM: [
      { code: "GAN1", name: "GANGTOK" },
      { code: "LACH", name: "LACHUNG" },
      { code: "MAN2", name: "MANGAN" },
      { code: "YUKS", name: "YUKSOM" },
    ],
    "WEST BENGAL": [
      { code: "ALIP", name: "ALIPURDUAR" },
      { code: "ARAM", name: "ARAMBAG" },
      { code: "ASAN", name: "ASANSOL" },
      { code: "BALU", name: "BALURGHAT" },
      { code: "BANO", name: "BANGAON" },
      { code: "BARD", name: "BARDHAMAN" },
      { code: "BASI", name: "BASIRHAT" },
      { code: "BEHA", name: "BEHARAMPUR" },
      { code: "BISH", name: "BISHNUPUR" },
      { code: "BOLP", name: "BOLPUR" },
      { code: "CANN", name: "CANNING" },
      { code: "CHHA", name: "CHHATNA" },
      { code: "CONT", name: "CONTIA" },
      { code: "DARJ", name: "DARJEELING" },
      { code: "DEBA", name: "DEBAGRAM" },
      { code: "DIAM", name: "DIAMONDH" },
      { code: "DINH", name: "DINHATA" },
      { code: "DURG", name: "DURGAPUR" },
      { code: "FALA", name: "FALAKATA" },
      { code: "JALP", name: "JALPAIGURI" },
      { code: "KARI", name: "KARIMPUR" },
      { code: "KAT1", name: "KATAMARI" },
      { code: "KHA1", name: "KHARAGPU" },
      { code: "KOLK", name: "KOLKATA" },
      { code: "KRIS", name: "KRISHNANAGAR" },
      { code: "KUMI", name: "KUMIRMARI" },
      { code: "LAL1", name: "LALGOLA" },
      { code: "MALB", name: "MALBAZAR" },
      { code: "MALD", name: "MALDA" },
      { code: "MANB", name: "MANBAZAR" },
      { code: "MOGR", name: "MOGRARA" },
      { code: "NAXA", name: "NAXALBARI" },
      { code: "PANS", name: "PANSKURA" },
      { code: "PURU", name: "PURULIYA" },
      { code: "RAI1", name: "RAIGANJ" },
      { code: "SAGA", name: "SAGARISL" },
      { code: "SAIN", name: "SAINTHIA" },
      { code: "SARE", name: "SARENGA" },
    ],
     JHARKHAND: [
      { name: "BAGODHAR", code: "BAAR" },
      { name: "BARHAIT", code: "BARI" },
      { name: "BARWADIH", code: "BDIH" },
      { name: "BOKARO", code: "BORO" },
      { name: "BHAVANATHAPURI", code: "BPUR" },
      { name: "CHATRA", code: "CHAT" },
      { name: "CHITARPUR", code: "CHI1" },
      { name: "CHANDWA", code: "CHWA" },
      { name: "CHAKULIYA", code: "CHYA" },
      { name: "DHANBAD", code: "DBAD" },
      { name: "DEOGHAR", code: "DHA1" },
      { name: "DUMKA", code: "DMKA" },
      { name: "GIRDIH", code: "GDIH" },
      { name: "GUMLA", code: "GUMA" },
      { name: "HAZARIBAG", code: "HAAG" },
      { name: "HUSSAINABAD", code: "HUAD" },
      { name: "JAMSHEDPUR", code: "JAME" },
      { name: "JAMTARA", code: "JARA" },
      { name: "JAGANATHPUR", code: "JPUR" },
      { name: "JUMRI TALAIYA", code: "JUYA" },
      { name: "KHUNTPANI", code: "KANI" },
      { name: "MANOHARPUR SIG W", code: "MSIG" },
      { name: "PAKUR SADAR", code: "PAAR" },
      { name: "RANCHI", code: "RCHI" },
      { name: "SIMDEGA", code: "SEGA" },
      { name: "SUNDARPAHARI", code: "SUN1" },
      { name: "TAMAR", code: "TMAR" },
      { name: "TORPA", code: "TRPA" },
    ],
      LAKSHADWEEP: [
      { name: "AGATTI", code: "AGAT" },
      { name: "AMINI", code: "AMIN" },
      { name: "ANDROTH", code: "ANDR" },
      { name: "KAVARATTI", code: "KAVA" },
      { name: "MINICOY", code: "MINI" },
    ],
      "JAMMU & KASHMIR": [
      { name: "BANDIPURA", code: "BAR1" },
      { name: "DODA", code: "DODA" },
      { name: "DOORU", code: "DORU" },
      { name: "JAMMU", code: "JMMU" },
      { name: "KATHUA", code: "KHUA" },
      { name: "KISHTWAR", code: "KIAR" },
      { name: "KUPWARA", code: "KURA" },
      { name: "MAHORE", code: "MARE" },
      { name: "SONMARG", code: "SARG" },
      { name: "SHOPIAN", code: "SOPN" },
      { name: "SRINAGAR", code: "SRIN" },
      { name: "SUNDERBANI", code: "SUNI" },
      { name: "SURANKOTE", code: "SUTE" },
      { name: "TANMARG", code: "TANG" },
      { name: "UDHAMPUR", code: "UDHM" },
    ],
      LADAKH: [
      { name: "ABRAN", code: "ARAN" },
      { name: "BODHKHARBU", code: "BODH" },
      { name: "GYA", code: "GYAL" },
      { name: "HANUPATHA", code: "HNPA" },
      { name: "KARGIL", code: "KARG" },
      { name: "KIARI", code: "KIRI" },
      { name: "LEH", code: "LEH3" },
      { name: "PANG", code: "PAN1" },
      { name: "SANGRAH", code: "SAN1" },
      { name: "TANGTSE", code: "TANT" },
      { name: "Zangla", code: "ZANG" },
    ],
      "ANDAMAN & NICOBAR": [
      { name: "CAMPBELL BAY", code: "CAMP" },
      { name: "CAR NICOBAR", code: "CARN" },
      { name: "CHIDIYA TAPU", code: "CHID" },
      { name: "DHARMAPUR", code: "DHPR" },
      { name: "HUTBAY", code: "HUTB" },
      { name: "KADAMTALA", code: "KADM" },
      { name: "KAMROTA", code: "KAMR" },
      { name: "KILSHORI NAGAR", code: "KILS" },
      { name: "LONG ISLAND", code: "LOIS" },
      { name: "MAYABUNDAR", code: "MAYA" },
      { name: "PHOENIXBAY", code: "PBAY" },
      { name: "SHAHEED DWEEP", code: "SHA1" },
      { name: "SHOALBAY", code: "SHOL" },
      { name: "SITANAGAR", code: "SITA" },
      { name: "SOUTH CREEK", code: "SEEK" },
      { name: "SWARAJDWEEP", code: "SEEP" },
    ],
   



  }